### ISSUE TITLE
NHM 1.7.5.13 autoswitch issue with X11

### ISSUE THREAD

**Issue by Ravolta** [nicehash/NiceHashMiner-Archived#1009]
I notice that if i am running Claymore's Dagger/Decred miner and miner switches to (sgminer) X11 and then back to Claymore's D/D. The NHM does not terminate the X11 miner properly. Instead the X11 keeps running at the background with the D/D miner.

If it helps anything the log shows something like this:

[log1.txt](https://github.com/nicehash/NiceHashMiner/files/1067229/log1.txt)

**Comment by S74nk0** [comment]
@Ravolta We have made 3 releases with v1.7.5.13. Looking from the log it seems (I can see this since there is no msg on trying to kill the sgminer process) you have the first revision that one has an issue with closing mining windows. Download NHM v1.7.5.13 again (private browsing or different user, just make sure to download the new one and not the existing one from the cache). Replace and run the miner and it should be working fine. 

Reopen the issue if this doesn't fix it. It could be related to driver version where sgminer hangs, you should look at [AMD-drivers-version-information](https://github.com/nicehash/NiceHashMiner/wiki/AMD-drivers-version-information)

Closing
