### ISSUE TITLE
Which parameter do I use to start minimizad?

### ISSUE THREAD

**Issue by y4rk** [nicehash/NiceHashMiner-Archived#1029]
Which parameter do I use to start minimizad?

**Comment by S74nk0** [comment]
@y4rk What would you want to start minimized?

**Comment by y4rk** [comment]
I would like to run in the background or that it initializes minimized because I put it on my server and I run the risk of someone closing the application

**Comment by y4rk** [comment]
I'm having another problem, I could not get it in the windows task scheduler. When you log on.

**Comment by S74nk0** [comment]
@y4rk Well since you are the owner of the servers 

> I put it on my server

 make sure to tell the people that have access or help you manage them, not to close NHM.
We will not include botnet friendly features since NHM is sadly being abused by botnets and is falsely being flagged by AV vendors as malware. So to reduce false flagging by AV vendors we will not implement botnet features.

Closing
