### ISSUE TITLE
ethminer.exe should be easily replaceable by most current version

### ISSUE THREAD

**Issue by mitbac** [nicehash/NiceHashMiner-Archived#1111]
specifically, "--dag-load-mode" is no longer an option in the most recent release of ethminer.

This is important because the most recent release of ethminer has as much as a 30% increase in performance for some pascal based nvidia gpu's.

**Comment by S74nk0** [comment]
@mitbac We have released [excavator_v1.2.9a](https://github.com/nicehash/excavator/releases/tag/v1.2.9a) and we will integrate it into NiceHash Miner 2. We are gradually dropping support for 3rd party (closed or open source) miners. The **--dag-load-mode** is from our [fork](https://github.com/nicehash/cpp-ethereum). We will not support **ethminer** anymore since we will be using [excavator_v1.2.9a](https://github.com/nicehash/excavator/releases/tag/v1.2.9a).

Closing issue...
