### ISSUE TITLE
Cant Withdraw

### ISSUE THREAD

**Issue by Aholicknight** [nicehash/NiceHashMiner-Archived#1150]
I have a lot of bitcoin. ![xck7mh7](https://user-images.githubusercontent.com/7843719/27980454-02cc1016-633c-11e7-9279-94ea19daecf3.png) and it dosent know how to withdraw. Does anyone know how to do this/fix it? thanks!

**Comment by mrfearless** [comment]
NiceHash will payout automatically to external wallet (or one hosted on NiceHash). 

But your balance needs to meet the threshold to pay out. [https://www.nicehash.com/?p=faq#faqs6](https://www.nicehash.com/?p=faq#faqs6)

As you have 0.00008346 BTC (0.08346 **m**BTC) which equates to 0.27 CAD you might have to wait a while till it hits the threshold of:
`0.00100000 BTC`

> Once per day for NiceHash-wallet unpaid balances, greater than 0.001 BTC

or:

`0.01000000 BTC`

> Once per week for external-wallet unpaid balances, greater than 0.01 BTC

**Comment by OneOfMany07** [comment]
Yep, you'll have "earned" some money, but since each transaction has a cost the server/host/pool waits to pay out until you have a good sized chunk.  I'm pretty sure you pay the transaction costs from the money you make so even if it lets you force a payout it often isn't a good idea (you'll lose more money that way).

**Comment by Aholicknight** [comment]
Thank you for telling me how to fix this. I litterally just noticed this and now im going to close it. Thank you!
