### ISSUE TITLE
cant copy the miner to desktop and riddled with viruses getting worse every release

### ISSUE THREAD

**Issue by keztheminer** [nicehash/NiceHashMiner-Archived#150]
i dont have permission to copy the file from my downloads to desktop and the viruses are getting worse and i will not use on my computer until these trojans are sorted upto 5 on this 1 download , my miner is off until this is sorted , so i am losing pennies and so are you

**Comment by tonyrayo** [comment]
This issue is completely unfounded (besides the fact that I believe NiceHash will be just fine without your "pennies"), assuming you are downloading the software from this GitHub release page, which is safe to assume.

In the last year that I've been involved with/used this project/application, there has never been, nor are there now, any viruses/trojans/malware/etc location either in the open-source code or packaging (I sometimes compile it myself after reviewing or making source code changes so I can say that with a good amount of certainty).  If you have any "viruses" or "trojans" on your computer, they did not come from this program.

That being said, in the past there have been nefarious hackers as well as system administrators that have placed mining software on computers without permission, so some anti-virus software might be reading your download as a false positive.  Unfortunately I cannot link you to an online scanner as they have size limitations (Metadefender allows for the largest public scanning of a file at 140MB, however the current package is slightly over 275MB when unpackaged).  If this changes, I will update my post.

**Comment by keztheminer** [comment]
https://www.metadefender.com/#!/results/file/1b29c58397694b2b90215a1aca6b0f24/regular/ this is result from your meta defender on the ccminer_sp.exe certainly the right attitude to distribute and deny  from above , i am out and will find someone that likes making pennies from me as pennies make pounds u know ,

**Comment by tonyrayo** [comment]
The 12 engines that showed an issue are the false positives I was referring to (compared to the 30 that marked the file as clean). If you take the time to examine those virus names, you will see that they are marked as "mining programs". I would suggest that you switch anti-virus programs or whitelist the files included in this package once you are satisfied that no harm is being done by them (which it isn't).
