### ISSUE TITLE
[Bug] Setting GUI always shows only one CPU tab

### ISSUE THREAD

**Issue by kuntan2237** [nicehash/NiceHashMiner-Archived#162]
Hi NiceHashMiner developers,
I found a bug for Setting GUI, following is the detailed info, could you help?
## Phenominon

While system have more than 1 processors, Main -> Setting GUI shows only one tab for CPU0 only
## Impact

All other CPUs can't be configured, for example, if we configure proxy in ExtraLaunchParameters field, only CPU0 will be enabled, the others are not.
## Wordaround

Change config.json directly works.

Thanks.

**Comment by nicehashdev** [comment]
Will take a look into this one and fix in upcoming version.

**Comment by S74nk0** [comment]
Hi @kuntan2237. We believe this issue should be fixed in [NiceHashMiner v1.7.0.3-BETA](https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.3-BETA). If you have CPU and NVIDIA rigs I suggest that you give the BETA a try and report if this issue has been fixed. If you have AMD rigs I suggest you still use [NiceHash Miner v1.6.1.4](https://github.com/nicehash/NiceHashMiner/releases/tag/1.6.1.4) as it is more stable for AMD devices at the time of writing. If you give a BETA a try and encounter any problems please open a new issue.
