### ISSUE TITLE
Gigabyte GTX 1070 G1 Gaming not working with Daggerhashimoto on Nicehash

### ISSUE THREAD

**Issue by nik13uin** [nicehash/NiceHashMiner-Archived#188]
Hello all,
I have four of Gigabyte GTX 1070 G1 Gaming OC 8GB on my MB Gigabyte GA-Z97X-SOC on Win7x64 with nvidia driver 372.54. Two of them are on PCI-e slots 1 and 3 inside PC box, and the other two are outside the box using extenders.
I have a problem with running Daggerhashimoto on NiceHashMiner_v1.6.1.2 and NiceHashMiner_v1.6.1.4  
When I try benchmark even only Daggerhashimoto, NiceHashMiner show me ''Disabled" instead of benchmark speed. The cards doesn't start benchmark at all. Even if I use extra options "--cuda-devices 0 1 2 3" I have no problems with lyra2rev2, lyra2re, neoscript etc. 
Is anybody encounter the same problem and would you help me correct it? 
Thank You in advance and kind reggards!
Niki

**Comment by S74nk0** [comment]
Hi @nik13uin . NiceHashMiner_v1.6.1.2 and NiceHashMiner_v1.6.1.4 do not support SM6.x officially and Daggerhashimoto is disabled. You can however try our public beta https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.1-BETA. This pre-release supports SM6.x cards and you will be able to mine Daggerhashimoto without problems. If you encounter any problems with the BETA release please open a new issue and we will fix it.

**Comment by nik13uin** [comment]
Thank You very much @S74nk0 . I will test it and I will share my experiences. The first thing I encounter is that when i start benchmark, only the first one GPU is accepted and start benchmark. My cards are the same, but from different merchants and first one is with different BIOS and memory chips - Micron. The other three are with Samsung. Why benchmark doesn't test all of my cards. This is problem i think. Thank You for now. 
Kind reggards!

**Comment by S74nk0** [comment]
@nik13uin Thanks for your feedback. Regarding same NVIDIA cards from different vendors/merchants (Asus/Evga/Gigabyte,...) you are right we should treat them as different card types and benchmark them separately, this will be fixed in the future release. As for the new benchmark strategy we made it the default to only benchmark unique devices to reduce benchmark time, but it seems that users also want an option to benchmark every single card on their system so we will probably add this option in the future as well. I will close this issue. If you encounter any more problems open a new issue.
Thanks again for your feedback.
