### ISSUE TITLE
[BUG] [1.7.0.1] only single GPU from group benchmarked

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#193]
running the benchmarks in a rig with 6x GTX 1060's results in the benchmark only using a single card, all others are idle

when starting the regular mining all cards are used however

**Comment by S74nk0** [comment]
Hi @felixbrucker. The new benchmark process only benchmarks unique devices to speed up the benchmark process and applies that benchmark to other cards that are of same type (instead of 6 benchmarks we have only one in your case). We might consider adding an additional option that would enable users to benchmark all devices regardless if they are same of same type.
