### ISSUE TITLE
[1.7.0.1] Benchmarking

### ISSUE THREAD

**Issue by phieti** [nicehash/NiceHashMiner-Archived#199]
When benchmarking nicehash miner only tests one GPU from rig (few GTX 1060s) , is it bug or feature?

**Comment by Virtix21** [comment]
I have an issue regarding this aswell, it seems it uses one of two GPU's in the system. Two show up in the tab, but both are the same physically.

**Comment by S74nk0** [comment]
We made the new benchmark strategy to benchmark only unique device types. So if you have for example 6 graphics cards and 3 of them are GTX 970 and 3 GTX 960, there would be only two benchmarks and apply those to same cards (reducing benchmark time). To reduce confusion we will be removing this feature in the next release since most users regarded this as a BUG, and some users expressed that they want to benchmark all cards. We might reintroduce this feature in a far upcoming release.

**Comment by phieti** [comment]
I think it good feature, but having sum of 3 GPUs hashrate as in your example would be less misleading i think. Also please bring back "start mining on program start" option.

**Comment by S74nk0** [comment]
@phieti regarding benchmarks we made the option for users to copy benchmarks from other devices. [NiceHashMiner v1.7.0.3-BETA](https://github.com/nicehash/NiceHashMiner/releases/tag/v1.7.0.3-BETA). 
`start mining on program start` we will not be bringing this option back because of **botnet** exploits.
