### ISSUE TITLE
No X15 Support

### ISSUE THREAD

**Issue by ShibePrime** [nicehash/NiceHashMiner-Archived#20]
Is there plan to support x15?

**Comment by tonyrayo** [comment]
Both ccminer and sgminer support x15 (and have either directly in the base code or via specific forks for 18+ months), but [NiceHash](https://www.nicehash.com) is not running a x15 server at the moment.  I believe that it would be a trivial matter of adding the coin to NHM, however since it's not application related, I'd recommend bringing it up on the official [BitcoinTalk thread](https://bitcointalk.org/index.php?topic=562238.0) (or contacting the operators via the various other means as seen on the site) to get the ball rolling :smile: .

**Comment by ShibePrime** [comment]
I suppose I was confused as to why X15 was showing most profitable the other day on the nicehash homepage but not mine-able with NHM. 
I suppose if I wanted to mine x15 manually I could just point some devices to stratum+tcp://x15.usa.nicehash.com:3339

Sorry for the confusion. Still getting the hang of all this.

**Comment by tonyrayo** [comment]
My apologies, I was incorrect regarding NiceHash not having a X15 server (ugh I think I finally need glasses). I do not know why it is not included as an option in NHM. If it is not enabled in the mining apps (i.e. ccminer, sgminer, etc) then I'll see about merging X15 into the versions used for NHM. Again I apologize - my post was very misleading, thanks for bringing this subject up :bow: .

Edit: https://github.com/nicehash/cpuminer-multi <= CPU is already supported in the application used for CPU mining, however it's not configured to be enabled. I think I'll get more luck if I can talk to the almighty @kenshirothefist and/or @theLosers106 on IRC.

**Comment by kenshirothefist** [comment]
Sorry for the late answer. Well, X15 has been more or less without orders on NiceHash for the last half year, therefore it wasn't initially included in NiceHash Miner. Now it looks like it's getting hot again and we'll include X15 support in the next release, coming out probably at the end of next week. Nevertheless, all mining software, included in NHM (cpuminer, ccminer and sgminer) supports X15, therefore you can manually mine X15 with included mining software. Keep on mining and stay tuned for updates on Twitter @NiceHashMining ;)

**Comment by kenshirothefist** [comment]
Support for X15 algorithm has been added. See Releases.
