### ISSUE TITLE
Have 2 rx480, only mining with one.

### ISSUE THREAD

**Issue by steinhammer** [nicehash/NiceHashMiner-Archived#211]
I get error saying: "Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior 2, swapinterval 1, profile0).
This is most likely caused by not having the necessary graphics drivers installed"
One of the two cards work just fine.
Have tried allt the drivers listed on AMD now using 16.9.1 on win7. using amdcleanup.
[log.txt](https://github.com/nicehash/NiceHashMiner/files/461602/log.txt)

**Comment by S74nk0** [comment]
Hi @steinhammer. This issue will be fixed in the next release (NiceHash Miner v1.7.0.4), thanks for reporting. I see you are using NiceHashMiner v1.7.0.2-BETA, this version has been discontinued. I advise you to use NiceHashMiner v1.7.0.3-BETA for your CPU and NVIDIA cards as it has some known bug fixes. As for AMD if using NiceHashMiner v1.7.0.3-BETA I would advise that you only use it with DaggerHashimoto (it is and will probably be the most profitable algorithm for rx480 for a good while) and to enable them both add this line **--opencl-devices 0 1** to your settings for rx480 DaggerHashimoto algorithm under **Extra Launch Parameters**, this workaround should work. The NiceHashMiner v1.7.0.x-BETAs are not as stable for AMD cards at the time of writing, if you continue having problems with NiceHashMiner v1.7.0.x-BETA I advise you downgrade to NiceHashMiner v1.6.1.4 until a newer release. Sorry for your inconvenience and thanks again for reporting this major issue.
