### ISSUE TITLE
Can't open nicehash Error From_loading

### ISSUE THREAD

**Issue by fabien4455** [nicehash/NiceHashMiner-Archived#214]
![image](https://cloud.githubusercontent.com/assets/22091839/18376391/03b172f2-765f-11e6-8310-1c2df770f390.png)

**Comment by fabien4455** [comment]
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

*************\* Texte de l'exception **************
System.ArgumentException: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à NiceHashMiner.Configs.ConfigManager.LoadBenchmarks()
   à NiceHashMiner.Configs.ConfigManager.AfterDeviceQueryInitialization()
   à NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e)
   à System.Windows.Forms.Timer.OnTick(EventArgs e)
   à System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

NiceHashMiner
    Version de l'assembly : 1.7.0.3
    Version Win32 : 1.7.0.3

##     CodeBase : file:///C:/Users/Fab/Desktop/NiceHashMiner_v1.7.0.3-BETA/NiceHashMiner.exe

System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

Newtonsoft.Json
    Version de l'assembly : 7.0.0.0
    Version Win32 : 7.0.1.18622

##     CodeBase : file:///C:/Users/Fab/Desktop/NiceHashMiner_v1.7.0.3-BETA/Newtonsoft.Json.DLL

System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

log4net
    Version de l'assembly : 1.2.15.0
    Version Win32 : 1.2.15.0

##     CodeBase : file:///C:/Users/Fab/Desktop/NiceHashMiner_v1.7.0.3-BETA/log4net.DLL

System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll

MessageBoxManager
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0

##     CodeBase : file:///C:/Users/Fab/Desktop/NiceHashMiner_v1.7.0.3-BETA/MessageBoxManager.DLL

System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.6.1586.0 built by: NETFXREL2

##     CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

**Comment by fabien4455** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/463235/log.txt)

**Comment by fabien4455** [comment]
Please help me ^^

**Comment by thanhhx** [comment]
## I also encountered similar problems. Help me!

Log:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
*************\* Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NiceHashMiner.Miners.MinersManager.GetEnabledDeviceProifitDictionary(Dictionary`2 speedDict, Dictionary`2 NiceHashData)
   at NiceHashMiner.Miners.MinersManager.SwichMostProfitableGroupUpMethod(Dictionary`2 NiceHashData)
   at NiceHashMiner.Form_Main.SMAMinerCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

NiceHashMiner
    Assembly Version: 1.7.0.1
    Win32 Version: 1.7.0.1

##     CodeBase: file:///C:/Users/thanh/Pictures/NiceHashMiner_v1.7.0.1-BETA/NiceHashMiner.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622

##     CodeBase: file:///C:/Users/thanh/Pictures/NiceHashMiner_v1.7.0.1-BETA/Newtonsoft.Json.DLL

System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0

##     CodeBase: file:///C:/Users/thanh/Pictures/NiceHashMiner_v1.7.0.1-BETA/log4net.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

MessageBoxManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0

##     CodeBase: file:///C:/Users/thanh/Pictures/NiceHashMiner_v1.7.0.1-BETA/MessageBoxManager.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
For example:
<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by S74nk0** [comment]
Hi @fabien4455. I see you have an AMD rig. I would advise you to use [NiceHash Miner v1.6.1.4](https://github.com/nicehash/NiceHashMiner/releases/tag/1.6.1.4) at the moment of writing since the new BETAs are not as stable and can cause problems with AMD setups.

Hi @thanhhx. Can you please post the log.txt file under \logs\log.txt

**Comment by S74nk0** [comment]
This is fixed in new stable releases.
