### ISSUE TITLE
Nice Hash Miner closes when it hits 4.66% miner unzipping 

### ISSUE THREAD

**Issue by trustedalliance** [nicehash/NiceHashMiner-Archived#219]
[Windows 10 64bit] So basically I’ve been using nice hash for about three days and I’ve racked up about $1.40 but when I went to get on one day it wouldn’t open for some reason- so I redownloaded it and I got a ‘could not execute’ whenever I tried to extract it. I asked the twitter page and they suggested I use a different .zip opener so I used WinZip, 7-Zip and some others but still no luck. So then I downloaded the 1.7.0.4 or whatever the beta was and I could finally extract it without any problems. Though when I ran the NiceHashMiner.exe it went normally until it was unzipping the miners it left the bin.zip and created a bin folder within but stopped extracting the miners at 4.66%... Any ideas? (In the log I tried to go without wifi for the download part.) 
[log.txt](https://github.com/nicehash/NiceHashMiner/files/471107/log.txt)

**Comment by S74nk0** [comment]
Hi @trustedalliance. This could be an issue with the antivirus software, reporting false-positives. The problem is that CPU miner programs (and sometimes GPU miners), are flagged by some AV software. Reason for this is because there were cases where people bundled miner software into their malware to mine on infected machines when they are idle and gain profit for themselves. Because all the miner source code is public domain and open source this means that anybody can take it and re-purpose it for their needs and the AV detection systems mostly looks for same binary patterns, and because the source and binaries are from the same GPL sources it falsely classifies mining software as malicious, where only the malware code is malicious. What AV software are you using?

**Comment by Abdulsyukur** [comment]
<br class="Apple-interchange-newline"><div id="inner-editor"></div>how to update the version v1.6.1.4 bev1.7.1.4? 

    Pada Kamis, 15 September 2016 15:57, Stanko Krstić <notifications@github.com> menulis:
 

 Hi @trustedalliance. This could be an issue with the antivirus software, reporting false-positives. The problem is that CPU miner programs (and sometimes GPU miners), are flagged by some AV software. Reason for this is because there were cases where people bundled miner software into their malware to mine on infected machines when they are idle and gain profit for themselves. Because all the miner source code is public domain and open source this means that anybody can take it and re-purpose it for their needs and the AV detection systems mostly looks for same binary patterns, and because the source and binaries are from the same GPL sources it falsely classifies mining software as malicious, where only the malware code is malicious. What AV software are you using?—

**Comment by trustedalliance** [comment]
@S74nk0 I've got McAfee

**Comment by nicehashdev** [comment]
We suggest you to disable AV due to known problems of AVs false tagging mining software.
