### ISSUE TITLE
NiceHash Miner v1.7.1.3 is totally fucked

### ISSUE THREAD

**Issue by Singman33** [nicehash/NiceHashMiner-Archived#231]
Great performance !
You have totally fucked v1.7.7.1.3 :
Nothing is displayed when benchmarking, no list to select algos, no result.
Log is written with binary NULL char.

Guys, be serious, before committing a version, test it in 2 or 3 differents configurations !

**Comment by felixbrucker** [comment]
for me it is working fine, might help to clear any previous config (just copy it somewhere for backup) and start fresh

**Comment by Singman33** [comment]
Already done. Fresh new directory.
Look like a printing bug, the program work but nothing is displayed on benchmark, and that dont explain the log file bug.

[log.txt](https://github.com/nicehash/NiceHashMiner/files/478109/log.txt)

**Comment by felixbrucker** [comment]
this is indeed strange, my log is fine (no null chars) and benchmarks are displayed like so:

![unbenannt](https://cloud.githubusercontent.com/assets/5189997/18607971/6146a3b4-7cdc-11e6-99f1-22ef0971c850.PNG)

im using win8.1 x64

what OS are you using? might be software related to your environment

**Comment by Singman33** [comment]
Windows 10 64-bits, have no problems in previous beta

**Comment by felixbrucker** [comment]
i dont have win10 at hand, maybe someone can confirm its not win10 related but something else, or devs can figure what its related to from log

**Comment by xadonxander** [comment]
3 computers, Windows 10 pro 64 bit, windows 10 pro 64 bit, windows 10 home 64 bit. All display nothing in the benchmark screen. It seems to work fine just does not show or allow selection the algorithm on the benchmark screen.
![screen](https://cloud.githubusercontent.com/assets/2667712/18608738/2991d2c4-7cb7-11e6-9380-f9a00fe2e063.jpg)

**Comment by felixbrucker** [comment]
also after you click on one of those Devices?

**Comment by felixbrucker** [comment]
interestingly the device enable toggle is missing in your screen

**Comment by snowcrawl** [comment]
I am trying the benchmark, but on lbry it seems to get stuck.  I am then not permitted to launch my GPU miner, only the CPU miner works, so I will have to use the previous release for now.

**Comment by S74nk0** [comment]
Hi guys. Algorithms missing from the benchmarks is a serious issue and we are investigating this problem. It seems to be a windows forms issue since some setups work and others don't and it would be helpful for people that have this problem to report what .NET framework is used what OS and maybe provide the logs (logs will probably not be of any significant help here). Please report if you can disable or enable algorithms from the settings menu under **Device/Algorithms** tab, and if this issue happens also there (if it works in settings you can use it as a workaround until we fix this problem). 
@felixbrucker 

> interestingly the device enable toggle is missing in your screen

this is expected since he is in the middle of benchmarking and when in benchmark there is no option to enable/disable devices since they are in use.

@snowcrawl please provide the log file so we can see what video card are you using for **lbry** and what video drivers. If benchmarking **lbry** fails you can try disabling it in the settings from under **Device/Algorithms** tab so you can use your GPU for mining other algorithms.

**Comment by xadonxander** [comment]
I updated all my drivers and everything is working again. Apparently win 10 downloaded the anniversary update without my knowledge. I had the same issue with lbry after the driver update. I also got an error about files missing check your virus scanner. I deleted the directory and started over with a fresh download and now everything works.

**Comment by snowcrawl** [comment]
I did what someone suggested above, delete v1.7.1.3 and then extract it and try again.  On the second try I did get it to work, after noticing that my antivirus program was interfering with the benchmark process, based on looking at the log.  Once I disabled the antivirus, the benchmark went through without any problems.  I am running a Radeon R9 380, so at this point in time I am going to running daggerhashimoto 100% of the time anyways, since nothing else comes close in terms of profitability for this card.   Although I am finding that the CPU mining seems to actually be working better for me on this release.  I never bothered using it in the past because I had the impression that it was slowing down my GPU mining performance, as though I was losing about 1 MH/s.  Now it looks like it isn't affecting it, and yielding a slightly higher profit per day (CPU)  than on the previous version.

**Comment by felixbrucker** [comment]
@snowcrawl it now uses cpuminer-opt (https://bitcointalk.org/index.php?topic=1326803.0)

**Comment by hinzatoni** [comment]
Yeah it works fine for me too. I cleared previous config just in case,
works like a charm right away

2016-09-17 9:54 GMT+02:00 Singman33 notifications@github.com:

**Comment by S74nk0** [comment]
Hi guys. We still could not reproduce this issue on our testing machines. For all the users that had missing algorithm list in Benchmarks and Settings please try these patched versions and report if any of them fixes the problem. To test them just copy the *.exe files in the NiceHashMinerv1.7.1.3 folder. Thanks!
[NiceHashMiner_ALV_patched.zip](https://github.com/nicehash/NiceHashMiner/files/483655/NiceHashMiner_ALV_patched.zip)

**Comment by nicehashdev** [comment]
Please, use latest version and reopen if you still have issues with this.

**Comment by budjoni** [comment]
hello guys i have prob with my nicehash program when i update him hi say after five minute mining to turn off Algorithm daggerhashimoto in benchmark/setings but when i go there i cant find that algorithm can someon help me ty .  I have just 1 rx 470 with old nice hash i was have 220 h/s now there was say to i have 540 h/s but its same money making per day .
