### ISSUE TITLE
[1.7.0.1+] Video controler is not ok

### ISSUE THREAD

**Issue by phieti** [nicehash/NiceHashMiner-Archived#232]
Can we have this warning beign removed or get it autoclosed? Its messing up with auto mining

**Comment by S74nk0** [comment]
Hello @phieti. We will fix this in the upcoming release, as you probably know auto mining was disabled for a while because of botnet concerns and when we reintroduced this feature this was not taken into account. Next release will be fixed with **Show Driver Version Warning** or a new setting just for this.

**Comment by S74nk0** [comment]
This will be available in the next release. I will close this issue.
