### ISSUE TITLE
NHM 1.7.1.3 several options needed

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#235]
Hi!
I have some wishes for adding to NHM.
1. Please, add an option to group/ungroup devices for mining together/discrete.
2. Please, add an option to disable AMD temperature control.
3. In 1.7.1.3 several selected devices mines together same algo through 1 miner, but additional parameters used for group mining is taken from 1st device. It's need to add for sgminer double or more addiotional options for every GPU, f.e. "--xintensity 512, 256" for 2 GPUs - 1st is 512 and 2nd 256.
4. When ethminer.exe used for mining 2+ GPUs additional parameters taken from 1st GPU too. It's need to calculate average additional parameters to mine in group, f.e. 1st GPU have "--cl-global-work 20480 --cl-local-work 256", 2nd GPU have "--cl-global-work 12800 --cl-local-work 128". Calculating average parameters for group mining:
20480+12800 / 2 = 16640
256 + 128 / 2 = 192
Resulting parameters for group mining will be --cl-global-work 16640 --cl-local-work 192.

Thanks a lot for your work!

**Comment by rfariavitor** [comment]
"2. Please, add an option to disable AMD temperature control."
We need it soon. AMD tempcontrol on NHM isn't working well. Actually it's never worked well, but in previous version there was a way to disable it.

**Comment by S74nk0** [comment]
Hi @UnclWish. I have read your previous issue that is closed now so I will respond here.
Regarding features here are the answers for our future plans:
`1. Please, add an option to group/ungroup devices for mining together/discrete.`
We probably won't be adding this in the next release or at all since our goal is to make NHM **Plug&Play** as much as possible, and this feature would probably confuse new users and it won't be needed (why not will be clear in other answers).
`2. Please, add an option to disable AMD temperature control.`
We will reintroduce this feature with the default settings to enable or disable or update ExtraLaunchParameters to handle this as well.
As for 3. and 4. 
You are absolutely right this will be fixed. ExtraLaunchParameters will be per device like they are now but the grouping logic will be smarter. You will set parameters per individual device for desired algorithms and we will group them accordingly. For examle if we have 3 devices with setting like so for algorithms A and B:
- device1 --xintensity 1024 --worksize 64 --gputhreads 2
- device2 --xintensity 512 --worksize 128 --gputhreads 2
- device3 --xintensity 512 --worksize 64 --gputhreads 4

if A is most profitable for device1 and device2 and B for device3 the NHM will run two sgminers for A and B like so:
- sgminer .. --xintensity 1024,512 --worksize 64,128 --gputhreads 2,2 .. (device1 and device2)
- sgminer .. --xintensity 512 --worksize 64 --gputhreads 4 .. (device3)

This feature is currently in development and testing but we will probably be introducing it a the next release (this is why we will not be including feature 1.)

**Comment by S74nk0** [comment]
A new version has been released with wanted features (**AMD temp reintroduced**) [v1.7.1.4](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.1.4). 

@UnclWish here is a short wiki on how to use [ExtraLaunchParameters](https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/README_ExtraLaunchParameters%20.md) in **v1.7.1.4**
