### ISSUE TITLE
Mining farm freezing

### ISSUE THREAD

**Issue by undefy** [nicehash/NiceHashMiner-Archived#279]
System specs:
Windows 7 64 bit 16 gig ram CPU Intel(R) Celeron(R) CPU G1850 @ 2.90GHz (2 CPUs), ~2.9GHz 6 card system 1 x r9 380 and 5 x 7950. Driver Version: 15.300.1025.0. NHM version 1.7.2.0

First problem:
Recently i am experiencing system freezes and crashes.... I do not not why but i noticed that after a couple of hours my CPU goes from about 50% to 100%, a message comes up that says thanks and please donate after that everything freezes and i have to reboot. Why is this happening?

Second problem:
I have bench marked all the algos but if i start to mine after a reboot straight away, the system freezes after 5-10 minutes. I have to re-bench at least one algo for it to start mining again without freezing. This used to work but now it freezes after 2-4 hours.

Third problem.
I do not see the algos to bench mark for my gpus. For the CPU there are 3 algos displayed.

A log file and a dxdiag file is attached.
[DxDiag.txt](https://github.com/nicehash/NiceHashMiner/files/551634/DxDiag.txt)
[log.1.txt](https://github.com/nicehash/NiceHashMiner/files/551635/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/551636/log.txt)

Hope to get your help and advice. As always awesome work!

**Comment by S74nk0** [comment]
Hi @undefy. I believe that the 3rd problem is fixed with the newer versions. The 2nd problem is related to #389 the newest release has most of the problematic algorithms removed. If you are still experiencing issues regarding to the 2nd problem write on #389. If you are experiencing issues described in 1st problem let us know. There are plans to make miner shutdowns graceful as of now they aren't and may cause driver failures.  
Closing issue...
