### ISSUE TITLE
[BUG] NHM 1.7.2.0 Crashes Nvidia Drivers

### ISSUE THREAD

**Issue by Dave-MNC** [nicehash/NiceHashMiner-Archived#283]
I have 2x 1080 and 1x 970 in my computer and the Nvidia drivers crash whenever NHM starts, or changes algorithms. This happens regardless of whether I choose, 1, 2 or all 3 GPU's.

Power supply is 1000 Watt Gold Rated.

Games work fine.

I have tried the following driver versions:
- 373.06
- 372.90
- 372.70
- 368.81

OS version is Windows 8.1 64 bit.

**Comment by S74nk0** [comment]
Hi @David2201.  `Nvidia drivers crash whenever NHM starts, or changes algorithms` If I understand correctly this happens when you start mining?

**Comment by someguy736** [comment]
I think I know why the program crashes, and perhaps why it doesn't work on newer drivers, for some people.

It appears Nvidia GPU Boost causes video card drivers to go crazy. I don't know why, but by forcing the GPU clock to a certain level at the launch of an application (I.E. unbounding GPU Boost or disabling it) NiceHash no longer causes crashes and I can even use some algorithms I had forsaken because of crashing.

To be clear, this problem has only ever happened for me with Nicehash, both on some older 660s and newer 1060s. I don't know if the 660s had GPU boost, but I know that by unbounding the OC value the 1060s no longer crash. I am also still testing at this point so your results may vary.

It's a fairly simple process, but I will break it down into some pretty easy-to-understand pieces (**lots** of steps). Get ready for a large wall of text.

Before continuing, it is important to mention a few things:
- By disabling GPU boost **you're effectively causing all programs which trigger the OC (pretty much everything) to overclock the GPU to max**. If you have electricity concerns, this fix may not work for you. 

- I have not been able to confirm if you can revert your GPU to a prior state with regard to GPU Boost (re-enable it). Theoretically it's possible, but the basic testing I have done after disabling boost has not provided any promising results. By that I mean I have not been able to re-enable boost at all. For me it's okay, but if that's a problem, you may not want to continue. 

- It is important to stress that you initiate this fix **AT YOUR OWN RISK**! I am fairly certain it just disables the boost, but you're working at a lower level than normal overclocking, so risks are implied.

- This has only been tested for a single GPU setup. For other setups consult the relevant documentation.
- See [https://devblogs.nvidia.com/parallelforall/increase-performance-gpu-boost-k80-autoboost/](url), [https://developer.nvidia.com/nvidia-system-management-interface](url) for more information:

Okay, so here's how you do it. Note that the basic principles are the same on other supported OS types, but for this little walkthrough I will be referencing Windows.
1.  First, create a batch file in the folder containing `nvidia-smi.exe`. You should have it as it's installed with the CUDA toolkit which I believe is required for all applications using CUDA. Mine was located in `C:\Program Files\NVIDIA Corporation\NVSMI`.
2. In the batch file, insert the following code:
```
@echo off
set nvidia-smi=C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe
"%nvidia-smi%" -pm ENABLED -i 0
"%nvidia-smi%" -q -i 0 -d SUPPORTED_CLOCKS
pause
exit
```
- ALWAYS RUN THE BATCH AS ADMINISTRATOR. It requires admin privileges to set the OC and do other various things.
- If you get the error message `Setting persistence mode is not supported for GPU (xXxx) on this platform`, disable or remove the line `"%nvidia-smi%" -pm ENABLED -i 0`
3. Run the batch. You should get a list of memory and GPU "values". These are clocks. Choose the values you wish to use (I used highest, but had to further overclock in afterburner for unknown reasons). The only GPU values you can use are the ones listed under the memory clock you also wish to use. Mixing and matching is not recommended.
4. After you've chosen your clocks, you can remove or disable the line `"%nvidia-smi%" -q -i 0 -d SUPPORTED_CLOCKS`
5. Now add the following lines, modifying as necessary:
```
"%nvidia-smi%" -ac (YOUR_MEMCLOCK),(YOUR_VIDCLOCK) -i 0
echo FINISHED!
pause
exit
```
6. The final product should look something like this:
```
@echo off
set nvidia-smi=C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe
REM "%nvidia-smi%" -pm ENABLED -i 0
REM "%nvidia-smi%" -q -i 0 -d SUPPORTED_CLOCKS
REM pause
"%nvidia-smi%" -ac 4004,1961 -i 0
echo FINISHED!
pause
exit
```
- Where `"%nvidia-smi%" -ac 4004,1961 -i 0` is equal to `"%nvidia-smi%" -ac (YOUR_MEMCLOCK),(YOUR_VIDCLOCK) -i 0`

- **TO CREATE A BATCH TO RE-ENABLE GPU BOOST, THEORETICALLY THE FOLLOWING CODE SHOULD WORK:**
```
@echo off
set nvidia-smi=C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe
"%nvidia-smi%" -rac -i 0
exit
```

7. You can now run the batch (unlocking your GPU) and run the executable for NiceHash directly (requiring manual boost deactivation as needed), or you can continue to the next step. Once the GPU is unbounded, it should stay that way. Perhaps even persisting through reboots.

8. Create yet another batch, this time in the same folder as your NiceHashMiner.exe client (`...\NiceHash Miner`).

9. In that batch, insert the following code, modifying as necessary:
```
@echo off
set niceHash=(YOUR_PATH_TO_NICEHASH)\NiceHashMiner.exe
set maxClockSet=C:\Program Files\NVIDIA Corporation\NVSMI\(YOUR_BATCH_FROM_PREVIOUS_STEPS).bat
runas /user:"(DOMAIN\USER)" "%maxClockSet%"
start "" "%niceHash%""
exit
```
- NEVER RUN THIS BATCH AS ADMINISTRATOR. I have had no luck launching the NiceHashMiner.exe client through an elevated command prompt. Your results may vary but save yourself the headache and don't.
- This method will require a password, but is by far the least intrusive method. You may want to search for an easier method.
- If you have a scheduled task that runs the maxClockSet batch, you can call that task instead of `runas` so you no longer need to input a password; use the following code instead:
```
@echo off
set niceHash=(YOUR_PATH_TO_NICEHASH)\NiceHashMiner.exe
schtasks /run /tn "(YOUR_TASK_NAME)"
start "" "%niceHash%""
exit
```

10. Run the batch instead of the executable directly and you're done!

**Comment by someguy736** [comment]
I have been trying to fix this same problem ever since I started mining. While I haven't completely stopped driver crashes, I have been able to minimize the instances of driver crashes, completely eliminate BSODs and stabilize my setup overall. Hopefully this helps you too.

First, a few things:
* As with any fix, **you apply these fixes at your own risk**.
* The fixes mentioned here have only been tested for a single GPU setup. For additional GPUs, consult the relevant documentation.
* The basic principles of the fix are the same over every supported operating system, however for this post I will only reference Windows and Batch.
* Your results may vary.

With that out of the way, let's get started.

1. To start, you'll want to _cleanly_ uninstall your current graphics driver with Display Driver Uninstaller (https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) or your software of choice. Here's a walkthrough:

```
1. Download and unpack DDU to your choice destination.
2. Run the DDU executable.
3. In the prompt, it should already have "restart in safe mode" selected. If not, select that option. DO NOT select a different option.
4. Restart the computer and finish as directed. If DDU doesn't start automatically on login, start it manually once you've reached the desktop.
5. Restart the computer, make it to the desktop, and wait for Windows to install the generic drivers for your GPU.
Finished!
```
* Once you've uninstalled the drivers cleanly, you can reinstall the latest stable drivers that are tested with NHM. To the best of my knowledge the latest driver in that category is driver version `372.54`. Of course, follow the directions and if the driver installation software _does not_ prompt you to restart, restart anyway.

2. Now you'll want to stabilize the system. This way, if a driver crash does occur it's less likely to cause a BSOD due to unresponsive behavior. To stabilize the system, we'll want to turn off the dynamic nature of GPU boost (if applicable). To read up on how to do this, see: https://devblogs.nvidia.com/parallelforall/increase-performance-gpu-boost-k80-autoboost/ and https://developer.nvidia.com/nvidia-system-management-interface and https://developer.nvidia.com/nvidia-management-library-nvml. Here's a walkthrough:
```
IF YOU DO NOT HAVE NVSMI INSTALLED ON YOUR COMPUTER, REFERENCE THE ABOVE LINKS OR ANY APPLICABLE DOCUMENTATION.
IT WAS INSTALLED FOR ME SO IF YOU NEED FURTHER HELP YOU'LL WANT TO SEARCH THE INTERNET FOR IT.

1. Navigate to your Nvidia System Management Interface folder. Mine was located at "C:\Program Files\NVIDIA Corporation\NVSMI"
2. Create a batch file. Name it whatever you want.
3. Inside the batch file, paste the following:

@echo off
set nvidia-smi=C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe
"%nvidia-smi%" -pm ENABLED -i 0
"%nvidia-smi%" -q -i 0 -d SUPPORTED_CLOCKS
pause
exit

4. Run the batch.
4.1) If you get an error that says something along the lines of 
"Setting persistence mode is not supported for GPU xXxx on this platform" 
remove the line ' "%nvidia-smi%" -pm ENABLED -i 0 '.

5. You should see a list of memory clocks with a list of supported GPU clocks below them. Pick the memory clock you want and then choose a GPU clock in that category you also want. 
6. After you've chosen your clocks, replace the text in the batch with the following:

@echo off
set nvidia-smi=C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe
"%nvidia-smi%" -ac (YOUR_MEM_CLOCK),(YOUR_GPU_CLOCK) -i 0
exit

7. Run the batch file.
```
* The process listed in the walkthrough should lock the GPU and memory clocks to the specified parameters until the driver is restarted. This will only happen when you restart the computer or the driver crashes. If you wish to unlock these parameters early, theoretically the following should work:
```
@echo off
set nvidia-smi=C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe
"%nvidia-smi%" -rac -i 0
exit
```

3. Next, we'll set the TDRTimeout value so that, theoretically, if the driver does crash, the operating system gives the driver more time to respond. This step is not strictly necessary as I didn't see any noticeable difference in performance when using it, however for the sake of being thorough you should do this step in case there was an effect. You can read up on the fix at the Microsoft website here: https://support.microsoft.com/en-us/help/2665946/-display-driver-stopped-responding-and-has-recovered-error-in-windows-7-or-windows-vista. 
* Note that this particular web page is designed **specifically for Windows 7 and Vista**. For other operating systems (like 8.1) you may want to do some internet searching. However as far as I am aware the fix is applicable for any Windows version above XP. 
* There is more than registry edits on this page, however you do not need to perform the others as I am absolutely sure they have no effect on the performance of the driver one way or the other.

4. Now, we'll want to make sure that the GPU is unlocked even if a driver malfunction occurs. To do this, enter the task scheduler and create a new task triggered by system display event 4101 with an action of starting the NVSMI batch file you (should have) created earlier. For a more detailed explanation, see the following picture gallery: https://postimg.org/gallery/zcuj4b0q.

5. Finally, you'll want to automate the process of the NHM both for starting it manually and automatically (like when a driver crash occurs or you first log in). To do this basically all you do is create a batch in the NHM folder which calls the NVSMI batch first and NiceHashMiner.exe second. Then you use the task manager to create a task with the exact same trigger as the NVSMI driver crash trigger we created in the previous step (or whatever trigger you'd like) with an action to start (and stop) the NiceHashMiner.exe program using the same batch we created in the NHM folder in this step.
* **For this particular batch process you NEED to run a scheduled task to call the NVSMI batch. Otherwise the batch, for some reason, won't navigate properly to the NHM folder**. Here's an example of a batch file for use inside the NHM folder:
```
@echo off
set nHDrive=C:
set niceHash=Program Files (x86)\NiceHash Miner\
set gpuUnlock=GPU Boost 'Disable'
SCHTASKS /Run /TN "%gpuUnlock%"
%nHDrive%
cd %niceHash%
start "" "NiceHashMiner.exe"
exit
```
* It is **very important** to make sure the task for starting the NiceHashMiner.exe program is set to only run when the user is logged in! GUI programs **SHOULD NEVER** be run through the task manager when the user is not logged in. Not just for security and stability reasons but also because their GUI won't show up if they are run in this manner. For a detailed explanation of both the task to start NHM on driver crash and the task to run NHM through batch initially, see the following picture gallery: https://postimg.org/gallery/d1i0hneg
* Also this should go without saying but of course make sure that NHM is set to start mining on startup.

As far as I can recall that's all I did.

**Comment by kenshirothefist** [comment]
This is driver related and not sure if we will be able to do anything about it. But this has now been added to our internal to-do. Thank you for your feedback!
