### ISSUE TITLE
GPU #0: result for 00000000 does not validate on CPU!

### ISSUE THREAD

**Issue by jpodcedensek** [nicehash/NiceHashMiner-Archived#284]
I wanted to try mining on my work computer before installing NiceHash to a more powerful computer (that gets cheaper electricity) and I am getting the following error: 

> GPU #0: result for 00000000 does not validate on CPU!

GPU is GTX 950 SC+ by EVGA, I am using NiceHash Miner v1.7.2.0

Edit: This happens when running default algorithm (lyra2re), if I disable it the next picked algorithm works fine.

**Comment by enavarrocu** [comment]
Same here with GTX 1050 Ti, NiceHash Miner 1.7.3.6.

Also the benchmark give crazy number as 61.710 GH/s.

**Comment by daflock** [comment]
I got the same probleme: 
 here with GTX 1050, NiceHash Miner 1.7.3.7
I id not fix it yet.....

**Comment by enavarrocu** [comment]
Yes the same with 1.7.3.7 also for me.

**Comment by S74nk0** [comment]
In order to fix this problem you can try lowering the GPU intensity instructions for this can be found [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) more specifically [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#nvidia-ccminers) since this is related to NVIDIA ccminer. The values differ by GPU model and manufacturer so some tweaking will be needed to find the right setting for your specific GPU. To set this value go under **Settings > Devices/Algorithms > _select GPU_ > _select lyra2re algorithm_ > _and set_ -i number** where **number** is in the range **[8.0-25.0]**.
Here is a picture as an example:
![lyre_i_flag_example](https://cloud.githubusercontent.com/assets/1517233/20711195/b2cbdee8-b63e-11e6-82f3-3c1d0f43a5e4.PNG)

Closing issue.

**Comment by daflock** [comment]
thank you very much.
Problem is fixed.
:-)

2016-11-29 14:19 GMT+01:00 Stanko Krstić <notifications@github.com>:

**Comment by OneOfMany07** [comment]
Why can't the app "auto-lower the intensity" when it sees this?  Seems like an obvious functional issue...
