### ISSUE TITLE
Start Fails - "Warning no device has been enabled for mining....."

### ISSUE THREAD

**Issue by Swimmer63** [nicehash/NiceHashMiner-Archived#303]
Attempting to mine without benchmarking (because it crashes) and I get this message.  Tried checking just one GPU, but got the same error.

![20161031 error](https://cloud.githubusercontent.com/assets/6272442/19875546/cc28fc7e-9f8a-11e6-8855-e3520dabe0f9.png)

**Comment by Swimmer63** [comment]
Using NiceHash Miner v1.7.3.1

**Comment by S74nk0** [comment]
Do a double check if any algorithm is enabled with those devices. It must be that algorithms got disabled and will not run because of it.

**Comment by DaaBoss** [comment]
See new bug report elsewhere today, Nov 2 --- this is duplicated below, since it is likely the same bug.

I've got quite a few PCs that work fine.  However, I have two different PCs, and neither of them will start, getting the same error, when Equihash only was chosen, CPU only.  It fails when trying to benchmark every time, no matter what.  Reinstalling doesn't help.  Also, if you try to bypass benchmark, it THEN tells you that you haven't chosen a device.  To ensure that it is not a settings issue, most everything is set to default.  Only CPU and Equihash chosen/checked.  Verified these were the settings in the config files.  Close the EXE and reopen.  Everything is checked properly, and it still says there is no device chosen for mining.

I suspect this is a bug that begins with not properly recognizing the CPU make and model, and then failing the benchmark tests as a result.   Further, the bypass the benchmark tests feature also fails to start the miner, giving a false error that no device was chosen, (when really, no benchmark was passed).  Giving up unless someone can solve this for two PCs.

**Comment by Swimmer63** [comment]
Thanks for responding.  Actually all four listed algorithms are checked and
can not be un-checked.
One of my thoughts was my pc was crashing because it was trying to test too
many algos.  But I can't uncheck any of them.  Clicking on the check box
next to the algos has no effect.

Thanks!
Mike

**Comment by cryptomonk** [comment]
same problem!

**Comment by Swimmer63** [comment]
Well since I got not meaningful response I switched to Claymore.  It's much
faster from what I hear anyway.

Thanks!
Mike

**Comment by S74nk0** [comment]
`Attempting to mine without benchmarking (because it crashes) and I get this message. ` Did not read it carefully the key issue **without benchmarking (because it crashes)**. In order for NHM to work a benchmark is needed to calculate profitability based on hardware speed. As for **benchmarks not working** this is still an open issue. More about it can be found [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389). Closing issue as it is related to the common opened issue regarding AMD.
