### ISSUE TITLE
Custom Temperature modifications

### ISSUE THREAD

**Issue by DaaBoss** [nicehash/NiceHashMiner-Archived#333]
I want to modify the temp for both GPU and CPU, hopefully independently.  Those of us who use a laptop might want to mine while it is producing more heat and noise, and less power than we'd like, and our only option today is to stop mining manually.  

- For comfort reasons, there are times I'd like to cut the heat in half in my laptop.
- For noise reasons, everyone around sometimes demands that the fans quiet themselves, so reducing the temp you stop mining for a limited time, would also accomplish this.
- For performance reasons, this would likewise stop mining, if I had other tasks that were increasing the 
CPU/GPU load.

I see three files, sgminer-fixed.conf in different folders that have the temp controls.  Which files should be modified?  All of them?  Since the variable settings are below, I assume if I simply subtracted the same number, 10-50, that this would accomplish my goal, without risking changing any other parameters.  Do these control both the CPU and the GPU? 

- "temp-cutoff" : "95",
- "temp-overheat" : "85",
- "temp-target" : "75",

 When starting the miner, it would also be nice to specify 30-100% performance.

**Comment by S74nk0** [comment]
@DaaBoss This can be done for AMD GPUs with algorithms that are using sgminer or Claymore's ZCash miner (more info about that can be found [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) and [sgminer here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#amd-sgminer-temperature-control-if-temperature-control-disabled-all-options-will-be-ignored) and [claymore here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#amd-claymorezcash-equihash)). The Claymore temperature settings cannot be set per GPU at the moment due to index miss-matching with OpenCL and ADL indexes (it is disabled to set per GPU because of stability). Including temperature control features for all devices and algorithms will not be available in the near future.

`When starting the miner, it would also be nice to specify 30-100% performance.` You can do this by setting the intensity parameters for ccminer and sgminer and other flags for other specific miners. All the instructions are available [here](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) the same link as the one for temperature settings.
