### ISSUE TITLE
[BUG] 1.7.3.4 eqm worker name

### ISSUE THREAD

**Issue by felixbrucker** [nicehash/NiceHashMiner-Archived#350]
upon starting eqm from NHM the worker name is ignored and "eqm1" is used

worker names worked for me with 1.0.1a when used manually (-w worker)

**Comment by S74nk0** [comment]
Hi @felixbrucker. It will be fixed in the future release. [this](https://github.com/nicehash/NiceHashMiner/commit/9e93c2e46574aaad8cd7228b9c2e517af1c80e80) commit fixes the issue. We will keep this open until the new official release.

**Comment by Justaphf** [comment]
To add to the issue reported here, I am not seeing any of my shares for equihash CPU mining displayed on the website since upgrading to 1.7.3.4 either (this affects speed, profitability, and unpaid balance--both tables and graphs).  Is this just a display bug on the website, or are those shares lost?

I have verified that downgrading back to 1.7.3.3 everything starts showing up on the website again.  For now leaving the client downgraded till the fix is officially released.

**Comment by ArtAnts1986** [comment]
> Is this just a display bug on the website, or are those shares lost?

the same question zkash new engine is not work or just not display?

**Comment by snowcrawl** [comment]
I downgraded back to 1.7.3.3 after trying to get this one to work for an hour.  This release was a complete mess for me.

**Comment by S74nk0** [comment]
New [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.3.5) fixes this issue.
@Justaphf and @ArtAnts1986 **eqm** didn't mine when miner window is hidden.

@snowcrawl sorry about that. Hope the new release will not cause problems

**Comment by Justaphf** [comment]
@S74nk0 thanks for the quick turnaround. I've upgraded and everything is running smoothly again!
