### ISSUE TITLE
EQM spawns window 1.7.3.7

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#380]
Even with "Hide mining window" checked in settings the EQM algo spawns a mining window. 
Win7-64, FX-8350, HD 7800

**Comment by SevenWhite7** [comment]
@thaistar 
The problem that your oversight with this has created, is that I like to have the 'auto start' feature active while reading, as I'll go entire minutes doing nothing but reading what's on my screen, researching.
You have no idea what a detriment it's been to have your obnoxious command window pop up over what I'm reading.
If you've decided that you simply must have the window pop up, at least have it start minimized so that it's out of the way of what I'm reading. It's still there, visible for safety, but not obnoxious and in the way, detrimental to computer use/activity.
