### ISSUE TITLE
Minimize EQM mining window

### ISSUE THREAD

**Issue by ghost** [nicehash/NiceHashMiner-Archived#381]
Since eqm will not run without its mining window open is it possible to have it default to minimized to not annoy PC users???
![image](https://cloud.githubusercontent.com/assets/7033982/20641166/f8695934-b3a6-11e6-9f07-4142ff4154f4.png)

**Comment by nicehashdev** [comment]
We get daily reports of NHM being installed on botnets.

That is why we are trying to make NHM to be visible to users, so that the user/owner of PC knows that NHM is running.

So on, in future, we will make NHM only more visible to the user and not less visible what you are trying to achieve.

**Comment by S74nk0** [comment]
Same issues:
#380 
#367 
#390

**Comment by SevenWhite7** [comment]
@nicehashdev 
The problem that your oversight with this has created, is that I like to have the 'auto start' feature active while reading, as I'll go entire minutes doing nothing but reading what's on my screen, researching.
You have no idea what a detriment it's been to have your obnoxious command window pop up over what I'm reading.
If you've decided that you simply must have the window pop up, at least have it start minimized so that it's out of the way of what I'm reading. It's still there, visible for safety, but not obnoxious and in the way, detrimental to computer use/activity.

**Comment by NTheZone** [comment]
This case should not be closed.  While I understand the security risks, I am in the same situation as nicehashdev.  Include some setting that can only be modified with a password, so that the pop-up windows is an option.  Please reconsider the closing fo this issue.
