### ISSUE TITLE
Nicehash miner windows does not honor Minimize mining windows setting for equihash miner

### ISSUE THREAD

**Issue by wildcat2020** [nicehash/NiceHashMiner-Archived#390]
From version 1.7.3.6 onwards, Nicehash miner windows does not honor Minimize mining windows setting for equihash miner

**Comment by nerdatwork** [comment]
People have been installing NHM on botnets so to make the owner of PC aware of mining the minimize windows option is disabled for equihash.

**Comment by SevenWhite7** [comment]
@wildcat2020 
@nerdatwork 
The problem that this oversight with this has created, is that I like to have the 'auto start' feature active while reading, as I'll go entire minutes doing nothing but reading what's on my screen, researching.
You have no idea what a detriment it's been to have your obnoxious command window pop up over what I'm reading.
If you've decided that you simply must have the window pop up, at least have it start minimized so that it's out of the way of what I'm reading. It's still there, visible for safety, but not obnoxious and in the way, detrimental to computer use/activity.

**Comment by NTheZone** [comment]
@SevenWhite7 @wildcat2020 
This annoys the heck out of me as well.  It can pop us when I'm showing a still image on my screen to a colleague, and they're like what is that?  If the command prompt window is minimized, it should keep minimized, not pop back up, and "steal focus"

**Comment by PhatWheZ** [comment]
I can agree with you on this one.
i have the same issue but only with XMR-STAK-CPU.

If this could be hidden and be run almost like a service would be amazing
