### ISSUE TITLE
Benchmark does not honor "Less Threads"

### ISSUE THREAD

**Issue by malafaya** [nicehash/NiceHashMiner-Archived#394]
I found out cryptonight CPU mining performance is best when using about 60% of max threads. So that's how I configured this algo: 5 "less threads" out of total 12 threads.
Nevertheless when benchmarking the miner still seems to use full CPU capacity and yields a lower benchmark result, likely skewing the algo selection optimizer when mining.
I believe the benchmark like the miner should also use all user's configs (and reset the benchmark result if it is changed).

**Comment by S74nk0** [comment]
Instead of setting LessThreads use the **-t 7** in extra launch parameters for **cryptonight**. The reason the LessThreads gets overriding is because when using this setting NHM tries lowering this automatically and finds the most optimal setting (it can fail if the computer is doing something CPU intensive in the background). If this is not working in your case then use the **-t 7** and it will not try to find the best setting but will use the users input one. 
Closing issue.
