### ISSUE TITLE
detecting  a nvidia x6 as a x5. 

### ISSUE THREAD

**Issue by althefirst** [nicehash/NiceHashMiner-Archived#399]
this version is detecting one GTX 1070 as a ( GTX 970 and also as a GTX 990) ie a nvidia x6 device as a nvidia x5

**Comment by S74nk0** [comment]
@althefirst this is very unlikely to be the case. The CudaDeviceDetection is identical. Provide logs or screenshots that clearly shows this issue.

**Comment by althefirst** [comment]
![nicehashminer 1738](https://cloud.githubusercontent.com/assets/20095115/20851803/1f3d9ee8-b8a8-11e6-9d30-3817ac8ed40f.jpg)
![nicehashminer 1737](https://cloud.githubusercontent.com/assets/20095115/20851802/1f3bc924-b8a8-11e6-8420-a5f6c608b300.jpg)

**Comment by althefirst** [comment]
it is not good to say never

**Comment by althefirst** [comment]
oh and i have 5 different computers with 1 or 2 or 6 1070s in each one and all of them do the same.

**Comment by S74nk0** [comment]
`unlikely to be the case` not never :). This looks like that nothing is being mined (That is just a printing error from the stubs). What algorithms do you have enabled?

**Comment by S74nk0** [comment]
Post the logs. It will be easier to find out what is the problem here

**Comment by althefirst** [comment]
it wont mine because it thinks it see 2 nvidio x5 cards and not just 1 nvidia x6 1070
and it will not run a bench mark because it see 2 video cards when there is just one
![nicehashminer 1738-a](https://cloud.githubusercontent.com/assets/20095115/20852230/5a7d209e-b8aa-11e6-9f35-fc19a5b6cced.jpg)
![nicehash 1737 -a](https://cloud.githubusercontent.com/assets/20095115/20852229/5a7c62f8-b8aa-11e6-9847-0d45c495784d.jpg)

**Comment by S74nk0** [comment]
@althefirst please post the logs. It will give give us more information.

**Comment by althefirst** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/628386/log.txt)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/628391/log.txt)

**Comment by S74nk0** [comment]
@althefirst Thanks! Looking at the logs the detection seems to be fine
`GPU-13a2a5d5-7ed1-3eb7-a8a3-ea85ff4e4822 (NVIDIA GeForce GTX 1070):`
But I do see that there were a couple of summary read detection with ccminers only at the beginning and there are frequent switches. This must have been a rare case when the summary returned nothing and the default labels were not changed, or more likely that the frequent switching made this GUI error. The mining seems to be working fine based on the logs, **but I am a little worried that there are a lot of API read issues at every ccminer start** `GetAPIData reason: No connection could be made because the target machine actively refused it 127.0.0.1:4001`.

This could be an issue or just that the miner hasn't started the API read summary. If you can please check if the ccminers are running correctly when showing and when hiding the consoles. 
**Update** check if there are any differences when mining with hidden console windows and when shown and if the miners are actually mining.

**Comment by althefirst** [comment]
? i am not sure what your asking for, i don't code, i do scripts and hardware.
but yes because it see more then one video card with one a 1070 in the computer. when i run 1737 i have no problem. so even though it see just the 1070 in the log file some how when it reports to the GUI it is showing 2 strange GTX's

**Comment by althefirst** [comment]
? with 1738 no miner is running, it says it starts on the GUI but no console (cmd line window)

**Comment by althefirst** [comment]
oh i sent a log from the 1737 and the 1738. the one with the API's is from the working 1737 and those are from the daggmoto stop farm and the call to the new CMD window.

**Comment by althefirst** [comment]
looks like 1739 is working

**Comment by althefirst** [comment]
i did upgrade to the 28-nov nvidia driver but version is working with out problem
