### ISSUE TITLE
even though I have selected mine when idle, it's mining constantly. worked great before the update

### ISSUE THREAD

**Issue by easye35** [nicehash/NiceHashMiner-Archived#404]
opened a new one as somebody closed that last one without addressing the issue.  it still mines ALL the time. supposed to only mine when idle. It doesn't stop mining, ever. Please read ALL the issue before closing this again.
![screenshot_1](https://cloud.githubusercontent.com/assets/11009400/20853164/7d80c6f2-b8a7-11e6-8279-0ae6b62d1bdf.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/11009400/20853162/7d7fd602-b8a7-11e6-89b4-de32673fdf6c.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/11009400/20853163/7d809d1c-b8a7-11e6-8943-1bd22b82d6db.jpg)

How could there be a mining speed it I was using the computer to take the screenshot?

**Comment by S74nk0** [comment]
@easye35 Please post the logs. This will give us more information.

**Comment by easye35** [comment]
[log.txt](https://github.com/nicehash/NiceHashMiner/files/628462/log.txt)

**Comment by S74nk0** [comment]
I think I understand now what seems to be bothering you. The **Autostart Mining** handles the starting miner as **manual start** and to stop it it needs to be stopped manually (Clicking stop). This behavior was changed due to [this](https://github.com/nicehash/NiceHashMiner/issues/345). The previous complaint was that when starting mining manually it would stop when the machine was being used because of the **Start Mining When Idle** was enabled. Did I understand you correctly now?

**Comment by easye35** [comment]
yes, that is exactly what it's doing!!  I didn't know that was added... sorry

**Comment by S74nk0** [comment]
@easye35 No problem. I understand, the logic has been changed and it isn't working as expected.  There will be added updates/changes to this feature an issue is opened [here](https://github.com/nicehash/NiceHashMiner/issues/398). Since the current logic is not to your liking give us suggestions how to change it and we will take it into consideration. If the feature does not land in the next release it will in one of the future near releases. As I see it there also needs to be a setting how to handle auto-starting (is it manual start or idle)

**Comment by easye35** [comment]
really, all I would need is better explain how to set that up firstly. and maybe even some sort of 'light' so you know it's 'running but waiting for idle'.

**Comment by p1r473** [comment]
For me, I set idle to 5 seconds, I sit back and watch, and it won't idle. I am not doing anything! Not moving mouse or typing on keyboard.
idle detection hasn't worked in the last 2 versions for me. I have the option checked to mine when idle, but it won't start!
