### ISSUE TITLE
why cpu is not 100%

### ISSUE THREAD

**Issue by huidoo** [nicehash/NiceHashMiner-Archived#406]
why cpu is not 100%, 2cpus only 1pcu is used?

**Comment by De-Occultist** [comment]
Check https://github.com/nicehash/NiceHashMiner/issues/414#issuecomment-264685760 and make adjustments. Example for 2 x CPU, 2 cores per CPU with hyperthreading = 8 logical cores. I find that it performs better running only 4 threads instead of 8.

**Comment by huidoo** [comment]
well,maybe you are right.

**Comment by S74nk0** [comment]
CryptoNight on CPU performs better when using physical threads instead of using all hyper-threads. The exact number of threads can be set from **Extra Launch Parameters** to make it automatic set only **LessThreads** that will determine what is the best thread count for your CPU that will produce most hash rate.
