### ISSUE TITLE
ccminer and RX480 - error

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#413]
Use on Win7 x64, ram 12Gb
Bench on algo lyra2rev2 , decred , lbry - restart PC.
The error appears on two identical PCs

PS - The logs after this empty.

**Comment by ghost** [comment]
Do you have the latest driver installed???
non-whql-win7-64bit-radeon-software-crimson-16.11.5-nov25.exe

**Comment by foxwarernd** [comment]
Installed 16.11.3, on nhm 1.7.3.7 test ok, but 1.7.3.9 error

**Comment by S74nk0** [comment]
@foxwarernd do you mean sgminer (using only AMD GPUs)?

**Comment by S74nk0** [comment]
I am assuming this is related to **sgminer** and AMD RX480 (Ellesmere/Polaris) GPU. Disable all algorithms except **Equihash** and **DaggerHashimoto**. **sgminer** has been proven to be very unstable with these GPUs so in the future release (this [commit](https://github.com/nicehash/NiceHashMiner/commit/e1b91dd4b7fcab65efd415866edf0bbfe3fb524a)) if the GPU is code-name Ellesmere / architecture Polaris, **sgminer will be disabled** (until **sgminer is fixed**). Also this issue seems to be related to [this one](https://github.com/nicehash/NiceHashMiner/issues/389).
Closing issue...
