### ISSUE TITLE
CPU does not use all the core

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#414]
Win2008R2 System, CPU 2x Xeon E5405. On the bench it is clear that the use of all core (8 pieces), but at the start of operation is set -t option 6 and does not use all cores

[log.txt](https://github.com/nicehash/NiceHashMiner/files/628748/log.txt)

**Comment by De-Occultist** [comment]
Try editing the file configs/benchmark_GEN-{HWID}.json   

"CryptoNight": {
      "NiceHashID": 87,
      "MinerName": "cryptonight",
      "BenchmarkSpeed": 170.0,
      "ExtraLaunchParameters": "",
      "Skip": false,
      "LessThreads": 2

Change LessThreads to 0 and restart NiceHash

**Comment by S74nk0** [comment]
CryptoNight on CPU performs better when using physical threads instead of using all hyper-threads. The exact number of threads can be set from **Extra Launch Parameters** to make it automatic set only **LessThreads** that will determine what is the best thread count for your CPU that will produce most hash rate.

**Comment by acerbr** [comment]
Both tips very nice.
Adjusted  an i7 for 6 threads instead of 10.
Got less cpu usage and faster hash
Tks
