### ISSUE TITLE
Nicehash Miner v1.7.3.9 Claymore takes a random port for monitoring

### ISSUE THREAD

**Issue by PauloOF** [nicehash/NiceHashMiner-Archived#416]
I could not set for example -mport -3333.
Is there a way to fix the monitoring port?

**Comment by S74nk0** [comment]
@PauloOF NiceHash Miner has changed the logic for setting monitoring ports because of different possible grouping combinations (if there are multiple GPUs that are different or have different settings), so the ports are random. They do have a starting port that can be set from **Settings > Advanced > API Bind port start pool**. However since there is [Algorithm ExtraLaunchParameters](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters) we can also add the **-mport** flag so that it could be deterministic. This might not land in the next release but it will be added in one of the near future releases.

**Comment by S74nk0** [comment]
@PauloOF this is fixed with the new [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.4). Here is the the [wiki](https://github.com/nicehash/NiceHashMiner/wiki/Reserving-API-bind-ports-(Advanced)) how to use it
