### ISSUE TITLE
Form_Loading ERROR!

### ISSUE THREAD

**Issue by TheAcogHero** [nicehash/NiceHashMiner-Archived#426]
I cannot start NiceHash Miner v1.7.3.9 on any of the 3 computers i just installed it on. Whenever i try to start the program, a window opens up titled Form_Loading, and says "Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. 

Method not found: 'Void
System.Globalization.CultureInfo.set_DefaultThreadCurrentCulture(System.Globalization.CultureInfo)'."

Then there is a drop down Details option that includes a whole bunch of stuff about 'just-in-time debugging. I have no idea what to do and i have nicehash miner running fine on 2 other computers. It just does not work on these 3. Please help!!

**Comment by TheAcogHero** [comment]
Forgot to mention that i did click 'Continue' and the dialog box just reappears immediately

**Comment by S74nk0** [comment]
@TheAcogHero this is due to not runing .NET45. This error appears (not always but sometimes) when there are .NET40 and .NET45 installed at the same time or if .NET45 is missing. We will be [falling back to .NET20](https://github.com/nicehash/NiceHashMiner/commit/a1f2a7f937d2d7d6178b00b976301a5b2641815e) as it turns out to be more stable. But in the mean time make sure you have .NET45 installed on your machines and uninstall .NET40.

**Comment by TheAcogHero** [comment]
Okay i will do that now

**Comment by TheAcogHero** [comment]
THANK YOU SO MUCH!!!
