### ISSUE TITLE
how ti fix nicehach miner bug

### ISSUE THREAD

**Issue by almoharebh** [nicehash/NiceHashMiner-Archived#441]
how to fix bug

**Comment by S74nk0** [comment]
The new version is out with many BUG fixes. Please try that and report if it fixes your issue. Also in the future please provide logs and detailed information (What GPUs/CPUs are you using, how much RAM does the system have, GPU RAM), motherboard, Operating System version and architecture...
All future issues without detailed information will be closed.

**Comment by almoharebh** [comment]
I use old Version I use GeForce NVidia 210 windows 10 Ram 4 Gigabyte

**Comment by S74nk0** [comment]
@almoharebh `GeForce NVidia 210` the GPU is too old (SM 1.2 version). The miner software will work for GPUs that are at least SM 2.1 and [higher](https://en.wikipedia.org/wiki/CUDA). Also 4GB RAM is bare minimum in order to have a good mining experience. Older hardware will not be supported in the future as they are not powerful enough.
