### ISSUE TITLE
extra param ?

### ISSUE THREAD

**Issue by foxwarernd** [nicehash/NiceHashMiner-Archived#459]
![11](https://cloud.githubusercontent.com/assets/19841581/21270898/a3c23a3a-c3c9-11e6-866c-54e4451f46e2.jpg)

Why are not considered additional parameters to be passed? Tried in different versions - all the time the final -tt1

**Comment by S74nk0** [comment]
The **-tt** parameter for Claymores miner is a temporary solution to apply **-tt** parameter with only one value and it is applied to all GPUs. This is due to an error with OpenCL and ADL indexing (**from Readme!!!** `NOTE: Check "KNOWN ISSUES" section. GPU indexes in temperature control sometimes don't match GPU indexes in mining!`). But it seems to be getting better with newer releases (Claymores miner) so it will be fixed in one of the future releases of NiceHash Miner.

**Comment by S74nk0** [comment]
This can now be edited by the user. [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.4). Here is the the [wiki](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#how-to-add-missing-miner-flag) how to use it.

If you have **any questions** please feel free to ask and we will update the wiki if things are unclear.
