### ISSUE TITLE
[request] multiple worker extensions

### ISSUE THREAD

**Issue by happyartifact** [nicehash/NiceHashMiner-Archived#510]
Is it possible to have a different worker name for CPU vs video miners?  I'd like to set something like worker1c and worker1v.

**Comment by S74nk0** [comment]
You mean per device? different GPUs and CPUs on same machine with different worker names?

**Comment by happyartifact** [comment]
Say I'm mining cryptonight with GPU and CPU on the same machine.  I'd like to set the CPU to a worker name, and the GPU to a different worker name.  Currently the GPU and CPU miners use the same worker extension, so they show up twice on the website with the same worker.

**Comment by S74nk0** [comment]
I understand. Currently all the running miners use the same worker name within NHM. This can be set separately when running manually, but that is not the point NHM should handle this. You are seeing two workers with same names because of two miner instances (I am aware that you already know this). We will discuss this and decide if there will be any changes. It might make sense to have a **machine worker name** and when running different miner instances on that machine to append a suffix to distinguish the miners. An example **rig02_cpu_0** and **rig02_gpu0** something like that. This feature will be discussed. I personally think it is a good feature.

**Comment by happyartifact** [comment]
I like your idea of a machine worker name and miner suffix better than mine.

**Comment by felixbrucker** [comment]
currently the worker char limit is too low to do something like R01-7970-1 or R01-280X-1
would love to see larger worker names supported independently of this issue :)

**Comment by kenshirothefist** [comment]
We will not support separate worker names for different devices, but we will consider extending worker names. This is not in our internal to-do, thanks for the feedback!

**Comment by SOFTSYNX** [comment]
with worker names just call each worker a different name and they wont be grouped and ur mining will be shown individualy in the nicehash miners list so eg worker1 worker2 so on and that way u know what each miner is doing

**Comment by SOFTSYNX** [comment]
and one more thing u can call workers any name u like does not have to be called worker1 thx
