### ISSUE TITLE
Nicehash miner speed not matching with web stats

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#516]
Hi

I get a constant 930sols/s on nicehash miner, but when I check my web stats it shows around 650/700sols/s. Is this normal or is something siphoning power? Profitability on Nichehash 4.3mbtc, on web 3.0mbtc.

**Comment by Johann1982** [comment]
Setup is as follows:

2x RX470 4GB
2x RX480 4GB
Win 8.1 x64
Crimson 16.10.3

**Comment by nerdatwork** [comment]
I second that, web stats do not match stats on NHM

**Comment by S74nk0** [comment]
There could be several issues here:
  - Some shares might not get accepted (look at the rejected percentage).
  - The other issue could be that the stats aren't mirrored instantly. When checking stats after about 10 minutes the values should be about the same (they can never be exactly the same due to network latency).
  - The miners might not work correctly with some specific driver version and are generating stales (this was the case with **ethminer** - [this commit](https://github.com/nicehash/NiceHashMiner/commit/c51e0cd3cf061731baa09e33209e92b36072d43a) should warn the user if the miner is working and not generating any shares)

This issue is partly covered by [this commit](https://github.com/nicehash/NiceHashMiner/commit/c51e0cd3cf061731baa09e33209e92b36072d43a) but there are still some things that need to be taken into account.

**Comment by Johann1982** [comment]
@S74nk0 Hi Stanko 
I don't get a lot of stales, maybe 1% or 2% rejected or stale. My average speed is 800sols/s plus as each of my 4x cards do around 220sols/s minimum. Will wait for next release to confirm. Will also format and re-install. 
Thanks for the reply. Cheers

**Comment by Johann1982** [comment]
@S74nk0 Hi Stanko
New release seems to have fixed this issue. Reporting on web stats seems to correspond with NHM.
Keep up the good work! Thanks
