### ISSUE TITLE
my cpu doesnt appear. Says NiceHashMiner doesnt support more then 64 virtual cores...

### ISSUE THREAD

**Issue by baalij** [nicehash/NiceHashMiner-Archived#525]
I have 2x Xeon 2697 v4 with 36cores and 72 threads in total. Not supported?

**Comment by S74nk0** [comment]
@baalij We will make an update or a separate version that will support your CPU(s).

**Comment by baalij** [comment]
@S74nk0 thank you! fast reply. Do you know when you are planing to do so?

**Comment by S74nk0** [comment]
@baalij Here: [NiceHashMiner_NO_CPU_LIMIT.zip](https://github.com/nicehash/NiceHashMiner/files/714109/NiceHashMiner_NO_CPU_LIMIT.zip). Now the main reason that more than 64HT cores are disabled is because of the affinity mask. There are two files in the zip. Try first the **NiceHashMiner_64HT_MASK** and then **NiceHashMiner_MORE_HT_MASK**. I hope they can still achieve full CPU speeds (please report back your speeds). As for bench-marking I suggest you manually set lessthreads for cryptonight algorithm to 36 (or the number of the physical cores per CPU do this for both CPUs). Lowering the lessthreads for equihash might also yield a better hashrate. Please report back the speeds (if they are equal per CPU) and if both versions work (and if there are any differences in benchmarked and mining speeds, check also the stats to see if they are equal).

**Comment by S74nk0** [comment]
@baalij no feedback... closing

**Comment by groovadelickun** [comment]
This has been working great with E7-4870 CPUs.   Thank you! :) 
Are there any plans for more updates that support more than 64 virtual cores?

**Comment by WarrenSchultz** [comment]
Got a chance to borrow a big quad box for a little while to see what happened using both EXEs linked above. I've got less threads 18 set and enable_ht=true in the additional params.
It throws all the work onto a single socket (with or without those parameters being set). 

Here's the kicker: Benchmarking works right. If I launch a single CPU from the UI, it appears to select the CPU properly, and also ok if I kick off a second instance and let it run individually. It only seems to have issues when all four CPUs are launched from the UI at the same time. 
![image](https://user-images.githubusercontent.com/8450968/28179474-134d82b0-67d0-11e7-8058-b35bf9d5fa9a.png)

![image](https://user-images.githubusercontent.com/8450968/28179531-420ed022-67d0-11e7-8952-1ee3a9fb2e9e.png)

**Comment by DeeViens** [comment]
Does this work with NHML 1.8.1.4 ?

nothing happens when I try to open NiceHashMiner_64HT_MASK or NiceHashMiner_MORE_HT_MASK

I put them in NHML 1.8.1.4 folder? or I'm doing something wrong...

I have 2x Xeon 2697 v4 with 36cores and 72 threads.

Thanks!
I am a beginner in this ;/
