### ISSUE TITLE
Nicehash 1.7.4.x + Nvidia GK104 GPUs 30% Drop in Performance on Cryptonight

### ISSUE THREAD

**Issue by moppidoo** [nicehash/NiceHashMiner-Archived#535]
Using the 1.7.4.x version on my GK104 GPUs, 1 GTX 680, 1 GTX 760 both GK104. I noticed a huge drop in performance not only in hashrate, but also overall desktop responsiveness.

Hashrate with 1.7.3.12 is approx 220/s+
Hashrate with 1.7.4.x is 150/s

1.7.4.x sets intensity at 8x32,8x24 automatically
1.7.3.12 sets intensity at 8x40

as manual parsing --launch parameter is disabled (I use 8x64,8x42 when not using Nicehash but it appears the ccminer/tsiv standalone won't get work from nicehash's cryptonight stratum that way.

atm I am less willing to upgrade to 1.7.4.x and stayed with 1.7.3.12 because with the above default intensity settings or some other causes, it's not worth to mine nor can I actually use my rig while mining since it's untweakable.

**Comment by S74nk0** [comment]
@moppidoo You can change the ccminer_cryptonight.exe in the bins folder with any other fork. The replacement miner is faster on newer GPUs, on old ones they can be slower. You can replace the old miner that was giving you better speeds. 
`as manual parsing --launch parameter is disabled (I use 8x64,8x42 when not using Nicehash but it appears the ccminer/tsiv standalone won't get work from nicehash's cryptonight stratum that way.`
We can enable this to work. The main reason it was disabled was due to high instability when passing params with older GPUs (when you have an SM3.0 and SM5.0 **combined** or higher version the system crashes). But if you know what you are doing this won't be a problem for you. In the next release there will be a setting to disable this **preventive measure**, and you can tweak parameters for SM2.1 and SM3.x GPUs.

**Comment by S74nk0** [comment]
[this commit](https://github.com/nicehash/NiceHashMiner/commit/27a22dfc47ba1ab3a8bf9c600e40c92fa80e5d5e) will solve this issue. Keep this issue opened until the next release.

**Comment by S74nk0** [comment]
The ability to set Cryptonight extra params on older SM version is available in the new [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2).
Closing issue...
