### ISSUE TITLE
Nicehash fails to load if elevated or run through task scheduler.

### ISSUE THREAD

**Issue by someguy736** [nicehash/NiceHashMiner-Archived#537]
As a part of automation of Nicehash I've needed to run it with several other commands. At one point, I needed to run it elevated. It would show up on the process manager, make it to ~11, 000 KB memory before just disappearing from the task manager. This could be bypassed by running a batch manually without elevation.

However now I am trying to use the task scheduler, without "highest privileges" checked, and the same thing happens; it'll load to about 11, 000 KB memory and then disappear from the task manager. No errors at all. This is regardless of if I run the Nicehash executable directly or if I attempt to use a batch file.

OS: Windows 7 Professional x64 SP1
CPU: Intel Core i7 870
RAM: 16 GB
GPU: NVIDIA GeForce GTX 1060
Driver Version: 372.54

**Comment by nerdatwork** [comment]
Are you trying automation to make sure if the computer crashes; you want it to start mining automatically ?

**Comment by someguy736** [comment]
Essentially. And not computer crashes; driver crashes only.

Basically the task would kill the nicehash program, wait 10-20 seconds (give the driver time to recover, if it will recover), and then reinitialize the nicehash program.

**Comment by nerdatwork** [comment]
I too am plagued with driver crashes so here is the trick I do:
Plug your HDMI cable to your card and monitor, overclock to your desired settings, switch to VGA mode by plugging monitor to VGA port on your mobo. Now start your miner and voila no more "Display driver has crashed and has recovered" messages. In order to autostart the miner after a computer crash most probably a BSOD; add the miner software/batch file to "C:\Users\ *YOUR-USERNAME* \AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"

**Comment by someguy736** [comment]
We're getting a bit off-topic here. I appreciate the suggestion, but this will not work for me.

**Comment by someguy736** [comment]
I'm not sure if it was this latest update or perhaps I was doing something wrong but the issue has been resolved.
