### ISSUE TITLE
daggerhashimoto algorithm comes and goes inconsistently from my GPUs

### ISSUE THREAD

**Issue by supertux1** [nicehash/NiceHashMiner-Archived#544]
I have six Radeon RX 480 GPU cards. Occasionally the daggerhasimoto algorithm shows up to be benchmarked, and I understand that it comes and goes as it becomes profitable. What is odd is that it does not show up as an available option for ALL my cards, only 5 out of 6 or 4 out of 6 sometimes. Is this a bug, or is the software doing it intentionally? (Split mining hashes?)

**Comment by S74nk0** [comment]
@supertux1 this was done intentionally since ethminer wasn't working correctly on newer drivers (especially on Windows 10). **ethminer** is now replaced with sgminer-gm that is faster and more stable. There was also a [patch](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.4.2) that fixes the new sgminer-gm benchmark accuracy. 
Closing issue...

**Comment by S74nk0** [comment]
P.S. GPUs need 2GB or more to work so your GPUs should work.
