### ISSUE TITLE
How to add extralaunch parameters for AMD OptiminerZ/Zcash v1.5.0 ?

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#545]
I enabled "AMD_Equihash_3rdParty": 1, in config. But how to add additional parameters for him?

**Comment by S74nk0** [comment]
@UnclWish I'll update the [wiki](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters)... but here are supported parameters https://github.com/nicehash/NiceHashMiner/blob/master/NiceHashMiner/Miners/Parsing/ExtraLaunchParametersParser.cs#L134. It is the same as all others in the settings select equihash and set in Extra Launch Parameters.

**Comment by UnclWish** [comment]
In previous version 1.7.4.1 these parameters was used only for Calymore's ZCash miner. In 1.7.4.2 they used by Optiminer too?

**Comment by S74nk0** [comment]
@UnclWish The UX is confusing but yes it is the same. If Optiminer is used than Claymore's parameters (most of them) will not have any effect. For a while there weren't more miners per algorithm but now there are and I can see it being confusing since the UX isn't meant to handle this. Just keep in mind when you use **Optiminer** all the equihash Extra Launch Parameters can have only **Optiminer** flags. It is the same with Claymore Cryptonight and sgminer-gm Cryptonight. If **"AMD_CryptoNight_ForceSgminer": true** all AMD Cryptonight Extra Launch Parameters can take only [sgminer](https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters#amd-sgminer) flags. When changing miners in the General.json it is best to do remove (make a backup) the benchmark files (Until this is fixed by NHM).

**Comment by UnclWish** [comment]
Ok. thanks.
