### ISSUE TITLE
Adding GPU2 broke all miners except equihash for GPU1

### ISSUE THREAD

**Issue by Meteorite777** [nicehash/NiceHashMiner-Archived#562]
**Issue:** Since adding a 1060 6GB to my rig, my 980Ti refuses to run on anything but equihash and daggerhashimoto. Neoscrypt, lyra2rev2, decred, cyptonight, and lbry all fail to benchmark on 17.4.2 and either say 'none' or terminated under speed. I still have my 17.4.1 benchmarks however it seems they no longer work and mining them throws an error quickly before restarting.

I was able to capture a glimpse of the error message on one of them and it threw an NVIDIA Cuda error “all CUDA-capable devices are busy or unavailable”. It also gave a specific line number but I lost the picture. I could probably capture it again on request if needed.

I have just done a clean install of the latest video driver and taken the cards out and switched their order and the problem persists.

The 1060 mines everything fine, and they can mine equihash just fine together. Luckily this isn't show stopping and happened to work out for the better since equihash is usually most profitable anyway, however I figured I should still post an issue about it.

**Comment by Pizzaguy1234** [comment]
Double check virtual mem has to be 8Gb or greater on multiple Gpu's.  I have rx470's and can only run equihash.  Just waiting for the next version of NHM.

**Comment by Meteorite777** [comment]
Interesting, thank you for the response! I hadn't heard about the virtual memory limit before but I saw Claymores AMD miner requires 16Gb for their AMD version. I am running Nvidia cards but I bumped my pagefile size to 16384-24576, currently sitting around 17GB allocated so I tried to re-run benchmarks and it seems issue persists.

**Comment by Pizzaguy1234** [comment]
Maybe don't use the latest and greatest driver, using ver 16.6 for my AMD's, and launching as admin with no av running on the program folder. Not sure if this is the best one but I have 2 GTX cards running NHM with ver 21.21.13.7290. date 9/16/2016 on another computer but they can't handle the equihash algo.  GTX 680, and 750.

**Comment by Meteorite777** [comment]
Alright thank you I suppose I did change my driver version from a stable older release to the newest one. I will try rolling back to an older version as well.

**Comment by djeep** [comment]
I am failing all CCminer-based benchmarks on my 980 Ti (Terminated / none) log shows 'CUDA Error'

System: Win10 64-bit / i7-2600k / single 980 Ti / NVIDIA Driver 378.49

Guessing its a driver issue, I'll attempt a rollback as well.

**Comment by bucketphobia** [comment]
I'm having the same issue.

Single GPU though, has anyone been able to fix it?

@djeep @Meteorite777

**Comment by nicehashdev** [comment]
Are you able to manually run any kind of mining app? This looks like an issue with drivers (is CUDA enabled?) or something not correctly installed. Are you able to play games normally?

**Comment by djeep** [comment]
Games as well as Equihash, Pascal, and X11Gost run fine, the issue seems to
be limited to ccminer variants.

**Comment by kenshirothefist** [comment]
Mixing different generations (i.e. Maxwell + Pascal) of GPUs in the same system could be problematic in some cases (even if it works in general - we also have working systems with mixed generation GPUs in our lab).

First of all make sure to try latest pre-release download: https://github.com/nicehash/NiceHashMiner/releases

What you can also try is to completely **uninstall all NVIDIA drivers and software** from your PC and then do a clean install of **latest official driver from http://www.nvidia.com**.

The various 'CUDA Error' are usually caused because of:
- incorrect or broken/badly installed driver (no support for CUDA8)
- overclocked GPUs
- failed/partly broken GPUs
- issues with PCIe slots on motherboards or PCIe Risers (if used).

You should check all these if you're still having issues.
