### ISSUE TITLE
Only 2 Algos for GPU?

### ISSUE THREAD

**Issue by trismegistis** [nicehash/NiceHashMiner-Archived#574]
Equihash and Zcash? Didnt there used to be ETH & others? Also why does zec miner crash my gpu driver?

**Comment by S74nk0** [comment]
@trismegistis I assume you have an AMD rig (please give more info, NHM ver., and HW). If you do have AMD then it is due to Drivers. If NHM (1.7.4.1+) detects newer drivers it will disable NeoScrypt and Lyra2REv2. You should also have CryptoNight, is it not in the list? DaggerHashimoto is disabled if the GPU has only 2GB RAM

**Comment by trismegistis** [comment]
Damn that must be it, I have rx 460, thought it was 4gb and is actually 2gb *fml* lol 

Perhaps the pc is blocking 2gb of its memory? If it was, how would I unlock it with windows cmd line? setx something I remember from mining eth last year but cant find the command,

**Comment by S74nk0** [comment]
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). There are new algorithms available.

Closing issue as it is related to old NHM version
