### ISSUE TITLE
sgminer for amd 480 or claymore?

### ISSUE THREAD

**Issue by tmslacker** [nicehash/NiceHashMiner-Archived#582]

**Comment by nerdatwork** [comment]
It is all up to you though, you can use sgminer since people say it is fast but I didnt see it as fast as people claim. In my case sgminer showed 0.5 Mh/s for quite some time so I decided to stick with ethminer. Claymore is overhyped because it can dual mine blah blah blah. But he charges 2.5% 'dev fee' so if you use claymore 2.5% dev fee + 3% NHM fee when you get paid in BTC.

**Comment by tmslacker** [comment]
Sgminer don't see any of my 480.  Maybe the Linux would be easier.

**Comment by nerdatwork** [comment]
Which driver version are you using ?

**Comment by tmslacker** [comment]
I tried the relive and the one recommended for the last update.  I've verified a clean install for both.  The miner only see the Intel HD Graphics.  Both driver sets cause no issues with any of the other miners.

**Comment by nerdatwork** [comment]
try the NON relive version specifically 16.11.5

**Comment by tmslacker** [comment]
That's the 2nd one I tried.

**Comment by tmslacker** [comment]
Win 10 x64 Ent.  5x AMD 480's.  SGMINER doesn't see my cards.  ADL =/= OPENCL.
