### ISSUE TITLE
1.7.4.4 small issues

### ISSUE THREAD

**Issue by thedirtybird** [nicehash/NiceHashMiner-Archived#585]
Does not benchmark Cryptonight on AMD 280x.. (using sgminer)
Also not happy that all benchmarking is not done on my account anymore...  Don't be greedy!!

**Comment by CAVACO-PT** [comment]
1.7.4.4

- Tested on 290x , 390x , 480 , Cryptonight (sgminer) doesnt benchmark in any card 
- OptiminerAMD does not work  also tested in 290x , 390x , 480 , 

![untitled](https://cloud.githubusercontent.com/assets/9946471/22630641/e986bfc4-ebf5-11e6-82b4-b97c7709a113.jpg)

**Comment by S74nk0** [comment]
From the readme files of 3rd party miners for Claymore Zcash and CryptoNight **Catalyst 15.12 drivers** are recommended (try using those drivers). Also there are some notes what GPUs might not work or what extra parameters need to be passed for them to work (check if your GPU might not be supported).

**Comment by fuzzfuzz** [comment]
It looks like the optiminer issues (confirmed here too) are due to the port being incorrect in the stratum address. Shouldn't it be 33357?
Can also confirm that a 7790, 270X, and 7750 with Radeon 15.12 do not benchmark on Cryptonight with sgminer - just sits there with no load on the GPU, forever. All work fine with Claymore.

**Comment by S74nk0** [comment]
This issue is fixed [commit](https://github.com/nicehash/NiceHashMiner/commit/37f376a0e0402c039583ac8624a60957517b1e59#diff-6037b4ae86b08bff6f3b3af044432902R20)
