### ISSUE TITLE
When Nicehash start mining, the GPU memory clock drops about 500mhz

### ISSUE THREAD

**Issue by NaitorStudios** [nicehash/NiceHashMiner-Archived#612]
This is a weird and unusual bug, that I've just noticed when I've replaced my motherboard, RAM and CPU.
I don't know what's the connection, but the only time that my GPU memory clock drops, is when Nicehash start to mine... My GPU is an GTX 1080 Founders Edition, no overclock.
The same happen when start any of the miners individually / manually.
(Nothing to do with mining threads, I've already tried with one)

**Comment by nicehashdev** [comment]
This is not related to NiceHashMiner, but it is a default behaviour for NVIDIA Pascal cards - memory is not running at full speed for CUDA processing. If you wish to change that, use 3rd party tools (such as Afterburner) and overclock your memory.

**Comment by NaitorStudios** [comment]
I'm pretty sure this wasn't happening before...
I recently replaced an AMD processor with Intel processor.
But, by using 3rd party tools to raise the memory clock, when I'm not using the miner it can overheat the VRMs and cause artefacts... Having to change the clock everytime I start to mine can be annoying.
Where have you seen about this behaviour? I've couldn't find anything about it.
I want to know what can make my clock drop beyond miners.

**Comment by dinicthis** [comment]
The problem is that no version of precision X or afterburner fixes this. I can set the memory clock so high it weirds out the display and crashes the computer.
But, if I start my nicehash first, then start my OC program, it drastically slashes memory speed down to 3000MHz and will never, ever, ever ever, ever, ever ever let it go back up until nicehash miner is turned off, then memory instantaneously skyrockets to the setting I have it on in PCOX.

So, once again, devs, you are wrong, and have not done your research, and do not know what you are talking about.

The PROBLEM, as usual, is with your software. YOU need to make it so it doesn't seize the memory controller and force it to the lowest possible setting.

The only program that does this is NHM.

**Comment by dinicthis** [comment]
Oh, and quit blaming anything and everything else when the problems is obviously your software. You are making, what 4 million dollars a month on this stuff? Grow up and fix it.

We need to be able to mine const effectively, and having to just dial up the overall power instead of being able to dial up the memory speed ONLY is a waste of power and money.

**Comment by dinicthis** [comment]
So to capsulize it so you can't pretend to not understand:
A. NHM software is the problem.
B. You need to fix it.
C. We want higher memory speeds and lower power draws, which we can do IF YOUR software was not blocking it from allowing higher memory speeds.

**Comment by 9dagothur9** [comment]
Having the same issue as of today. When mining, Afterburner shows 5000MHz clock, when closing NHM2 it shows 5500MHz. Same with legacy.
