### ISSUE TITLE
Start Mining When Idle doesn't work anymore?

### ISSUE THREAD

**Issue by rockie2015** [nicehash/NiceHashMiner-Archived#643]
Start Mining When Idle used to work before but with 1.7.5.0 it doesn't work anymore. It starts mining no matter if I am using the computer or not.

**Comment by S74nk0** [comment]
@rockie2015 from what version have you updated to 1.7.5.0?

**Comment by rockie2015** [comment]
I update every new version of NHM when they come out, it looks like that 1.7.4.5 has the same problem.

**Comment by S74nk0** [comment]
@rockie2015 do you have **Autostart Mining** enabled?

**Comment by rockie2015** [comment]
Yes, it is enabled. I tried both options: Autostart Mining enabled and disable but it still starts mining no matter what.

**Comment by S74nk0** [comment]
@rockie2015 Idle functionality was changed and it is a little confusing. When starting manually or when **Autostart Mining** is enabled it will ignore **Idle functionality** because it is understood that it is started manually ([issue](https://github.com/nicehash/NiceHashMiner/issues/398)). But if left running idle and after the idle time has passed it will start mining and when using the keyboard or mouse it will stop. Please try this and confirm it. When testing this works, but the change is that when starting manually (auto start or clicking manually start) it will ignore the idle functionality.

**Comment by rockie2015** [comment]
Oh I see. Now I leave Autostart Mining disabled and after the idle time has passed it started mining. Thank you for explanation!

**Comment by S74nk0** [comment]
[duplicate](https://github.com/nicehash/NiceHashMiner/issues/447).

Closing
