### ISSUE TITLE
Unable to mine using 980TI

### ISSUE THREAD

**Issue by bucketphobia** [nicehash/NiceHashMiner-Archived#674]
I am only able to mine using a few types, while others refuse to benchmark, and say "none"

Name | Results | Pastebin of benchmarks (for those that appeared as none.)
NeoScrypt, none (Unable to get the log because it crashes)
Lyra2REv2, none (http://pastebin.com/Jv7PN0Jy)
DaggerHashimoto, 0.881 MH/s
Decred, none (http://pastebin.com/FHwiEHSQ)
CryptoNight, none (http://pastebin.com/02NVGUUB)
Lbry, 78.060 MH/s
Equihash, 113.291 H/s
Pascal, 0.291 GH/s
X11Gost, 2.733 MH/s
X11Gost, 4.001 MH/s

**Comment by fefsf** [comment]
Wow, even for the ones you managed to benchmark those numbers are absolutely abysmal.

**Comment by bucketphobia** [comment]
@S74nk0 any ideas man?

**Comment by snowcrawl** [comment]
What kind of computer do you have your card connected to?  I do have a small form factor refurbished PC that is running an Nvidia GTX 1060 card.   I initially had trouble with it accepting the graphics driver.  When I ran the benchmark, one of the things I noticed was a very low DaggerHashimoto mining speed.   I think it was a combination of the driver not being fully accepted, and the onboard power from the motherboard not being adequate to power a high performance GPU connected to a PCIE x16 slot.   Every time I would reboot it would revert to where the driver had not been correctly installed, so the display would be in low resolution.   After playing around with reistalling the driver several times I finally got it to stick, and it now runs without fail.   The other key was that I had to connect the video card to a PCIE x1 slot because the onboard power supply is pretty weak.  This way you power the card externally with a separate power supply using a PCIE 1X riser adapter.

**Comment by nicehashdev** [comment]
These low speeds indicate issue with drivers or HW issues such as bad risers etc.
