### ISSUE TITLE
Daggerhashimoto website stats? not getting paid on that algorithm

### ISSUE THREAD

**Issue by navarrotarro** [nicehash/NiceHashMiner-Archived#678]
Hi dunno if its a bug that is only happening to me or others. But on the  "check my stats online" page there is no record of anything mined with that algorithm. If i only mine with that algorithm my profitability is 0 and left it like 10 minutes there and my unpaid balance didn't change

i have an rx 480

PD: on the nh app the profitability is normal. is just that aparently i'm not getting paid

**Comment by TheRigMaster369** [comment]
I have the same problem any answers ???

**Comment by giosal** [comment]
same here, but only with ethminer

**Comment by Romangino** [comment]
Same problem with the same GPU

**Comment by Johann1982** [comment]
Also, mininer window shows it is mining, but no stats on web.
@S74nk0 Any input please?

**Comment by S74nk0** [comment]
This issue is present with **AMD ethminer** when using newer drivers (there were complaints about it before). **ethminer** doesn't work correctly and is submitting stales with newer drivers. Because of this **AMD ethminer** will be dropped completely in the next release. [sgminer-gm v5.5.5-8](https://github.com/nicehash/sgminer-gm/releases/tag/5.5.5-8) will be used instead as an open source miner also **Claymore's Dual Ethereum** will be added as a 3rd party option (faster more stable miner).

To get around this issue disable **ethminer** and re-download the [bins package](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.1) or just download [sgminer-gm](https://github.com/nicehash/sgminer-gm/releases/download/5.5.5-8/sgminer-5.5.5-gm-nicehash-8-windows-amd64.zip) and replace it with the existing one. Please give feedback if the new **sgminer-gm v5.5.5-8** works correctly (check web stats when mining, wait about 10-15 minutes to see if full full speeds)

**Comment by Johann1982** [comment]
Thanks, will check and give feedback.

**Comment by giosal** [comment]
I just updated to sgminer-gm-5.5.5-8, it's mining at 26-27 MH/s but website shows average 17 MH/s, so it's showing smaller hashrate than miner (and it's more than 20%)
I did wait more than 15 min

**Comment by TheRigMaster369** [comment]
My input on this is that Nicehash is too lazy to investigate (Since Saturday) and has i use the miner and see that neither my miner or stats page is working i'm starting to believe that i'm not getting paid for my power and that nicehash is taking everyone's power in hashrate and is not been paying us the hashpower miners the right amount of money since the beginning.Which i'm confirming by using other sites miners that the hashrate is completely different from nicehash!

**Comment by S74nk0** [comment]
@giosal If it isn't averaged after 10-15minutes please check after 30minutes after that it should be the same. It depends with the miner really. **ethminer** has UDP packets and those aren't sent in order and stats speeds usually got averaged after 10-15minutes (30min for sure), it starts small and over time rises above the actual speed (accumulates sum for previously non shown) and drops to the actual speed. I am not sure how is the sgminer-gm implementation as I am not familiar with the source code for that miner. Claymore's Dual Ethereum seems to show averaged speeds after 3-6minutes (at least the tests I have done myself).

**Comment by platinum4** [comment]
sgminer's auto-fan control is basically useless

**Comment by platinum4** [comment]
[03:39:35] Started sgminer 5.5.5-gm-nicehash-8
[03:39:35] * using Jansson 2.7
[03:39:35] Probing for an alive pool
[03:39:35] Startup GPU initialization... Using settings from pool daggerhashimoto.usa.nicehash.com.
[03:39:35] Startup Pool No = 0
[03:39:35] daggerhashimoto.usa.nicehash.com difficulty changed to 0.400
[03:39:36] Building binary ethashHawaiigw128l4.bin
[03:39:36] Initialising kernel ethash.cl with nfactor 10, n 1024
[03:39:42] API running in local read access mode on port 4003 (16088)
[03:39:46] Waiting for work to be available from pools.
[03:40:12] Work available from pools, resuming.
[03:40:19] Error: clSetKernelArg of all params failed.
[03:40:19] GPU 0 failure, disabling!
[03:40:23] daggerhashimoto.usa.nicehash.com extranonce set to 0ce7c4

**Comment by platinum4** [comment]
w 192 crashes too; can't wait for the addition of a Claymore miner; those are generally stable.  I can't get any algorithm to work on sgminer except Decred or Pascal and when I run Pascal it just runs my VRMs right up to 95 because the fan just stays at 30

just realized I wasn't helpful by omitting 17.2.1 driver set, 15.12 is ok for daggerhashimoto in sgminer 5.5.5-gm-8

**Comment by giosal** [comment]
@S74nk0 yeah, I waited for a while, but average speed is still low, now aroung 18-19 MH/s
Will wait for dual miner

**Comment by S74nk0** [comment]
Try the [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre). Try using ClaymoreDual

**Comment by Johann1982** [comment]
Thanks Stanko

It seems to be stable and mining at a good speed. Been running for 3 hours
now and it is reporting the correct speeds to the web interface also.
Keep up the good work :)

Regards

Johann

**Comment by S74nk0** [comment]
This issue has been caused by **ethminer** and new AMD drivers. **ethminer** is discontinued for **AMD**.
Closing...
