### ISSUE TITLE
Dual Mining (Eth+PASC)

### ISSUE THREAD

**Issue by MoNTE48** [nicehash/NiceHashMiner-Archived#693]
Now I benefit from Dual Mining: Eth + Pasc. Do you plan to add Dual Mining support in Claymore Eth miner?

**Comment by gennadiv** [comment]
I agree with you, if possible, why not ++++

**Comment by gennadiv** [comment]
Етн + Pasc
Етн + dcr

**Comment by giosal** [comment]
@S74nk0 NHM sets ETH dual miner to ETH only. Do you plan enabling dual mining?

**Comment by giosal** [comment]
@S74nk0 another question:
**how is NHM passing options to Claymore ETH dual miner**? I tried adding -dpool etc. in extra options via settings page, but it didn't work as eth only option is hardcoded I assume.
Also, I checked different config files and start.bat in folder, they all are default.

**Comment by S74nk0** [comment]
Dual Mining DaggerHashimoto + [Pascal/Decred/...] will not be available **(at least not officially)** in the future pre-release / release. We can make [additional parameters](https://github.com/nicehash/NiceHashMiner/commit/38e3aaae218be9132a2466ca66b3f9f69387419b#diff-3ca7e2b0e91004f0f16ab9b71693cceeR218) that you can enter in ExtraLaunch Parameters parsable, so one can enable this **manually**. Try using [latest pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) version.

Closing...

**Comment by S74nk0** [comment]
@gennadiv [this version](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_7.zip) has some support for dual mining **(it will work but there are things to keep in mind)**.

You can pass: 
  - **-dual=Decred**
  - **-dual=Lbry**
  - **-dual=Pascal**

But please do keep in mind that there will be an additional developer fee that is 2.0% and not 1.0% when mining only Dagger. Also NHM will not show any stats regarding the second algorithm/coin, you will need to click **Check my stats online!** and there you will see what is the second algorithm stats. Also the estimated profit will differ since the second algorithm isn't taken into account.

**Comment by imrecsoka** [comment]
Hi sorry with the simple question but do you just add -dual=Decred    or do u add -mode 0    
im so confused now.

and is that it only, you only add -mode 0     OR    -dual-Decred in the    nicehashminer extra options?

**Comment by imrecsoka** [comment]
I find that those options dont all work for some reason.
and in certain nicehasminer versions none of them work at all
so yah thats not great at al to be honest especially when u are trying to figure out stuff and there are some that are out there willing to contribute and develop even better stuff towards nhm
