### ISSUE TITLE
dual

### ISSUE THREAD

**Issue by gennadiv** [nicehash/NiceHashMiner-Archived#695]
double production of ETN + Pasc
ETN + Decred
add

**Comment by S74nk0** [comment]
Dual Mining DaggerHashimoto + [Pascal/Decred/...] will not be available **(at least not officially)** in the future pre-release / release. We can make [additional parameters](https://github.com/nicehash/NiceHashMiner/commit/38e3aaae218be9132a2466ca66b3f9f69387419b#diff-3ca7e2b0e91004f0f16ab9b71693cceeR218) that you can enter in ExtraLaunch Parameters parsable, so one can enable this **manually**. Try using [latest pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) version.

Closing...

**Comment by S74nk0** [comment]
@gennadiv [this version](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_7.zip) has some support for dual mining **(it will work but there are things to keep in mind)**.

You can pass: 
  - **-dual=Decred**
  - **-dual=Lbry**
  - **-dual=Pascal**

But please do keep in mind that there will be an additional developer fee that is 2.0% and not 1.0% when mining only Dagger. Also NHM will not show any stats regarding the second algorithm/coin, you will need to click **Check my stats online!** and there you will see what is the second algorithm stats. Also the estimated profit will differ since the second algorithm isn't taken into account.
