### ISSUE TITLE
reRelease_5.zip-PreRelease_6.zip

### ISSUE THREAD

**Issue by gennadiv** [nicehash/NiceHashMiner-Archived#697]
of course zip 5 and 6 are the best options - but it would be better if the double Claymore Shelby machine two currencies - if not create the file yourself-after all, not everyone can

**Comment by S74nk0** [comment]
@gennadiv [this version](https://github.com/nicehash/NiceHashMiner/releases/download/1.7.5.2-pre/NiceHashMiner_v1.7.5.2_PreRelease_7.zip) has some support for dual mining **(it will work but there are things to keep in mind)**.

You can pass: 
  - **-dual=Decred**
  - **-dual=Lbry**
  - **-dual=Pascal**

But please do keep in mind that there will be an additional developer fee that is 2.0% and not 1.0% when mining only Dagger. Also NHM will not show any stats regarding the second algorithm/coin, you will need to click **Check my stats online!** and there you will see what is the second algorithm stats. Also the estimated profit will differ since the second algorithm isn't taken into account.

Closing...
