### ISSUE TITLE
GTX 1070 fans at full speed

### ISSUE THREAD

**Issue by Romangino** [nicehash/NiceHashMiner-Archived#705]
I start up my rig and everything runs fine, and the fans are normal but as soon as I launch eqm miner the rig freezes and the fans blast at 100%

**Comment by kenshirothefist** [comment]
Make sure you have up-to-date drivers and you are not overclocking your GPUs. Which version of NiceHash Miner are you using?

**Comment by Timoulis** [comment]
NHM is using 100% of the gpu. At least at my RX470. 
Maybe the fans work at 100% to cool down the temperature of the Gpu.
Check your temps. with Gpuz.

**Comment by fefsf** [comment]
Check your power cables for any signs of burning going to your video cards. I had the same issue when i started mining the fans would go haywire and windows would start crashing. Turns out the first link in the chain for my PCIE Riser power cable burnt out and caused everything else down the line (GPU's 4-6) to go crazy under load.

**Comment by Romangino** [comment]
@fefsf  Yea I think it was that. I unplugged and replugged everything, and it seems to be working fine for about a day now
