### ISSUE TITLE
NiceHashMiner.exe threat removed by AVG

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner-Archived#706]
So, starting from prerelease 7, AVG removes the exe file automatically...
Of course I can add it to exceptions, but, you know...

P.S. this happens when I launch NHM

**Comment by fefsf** [comment]
Its been like that forever now, i just dont use anti virus anymore :)

**Comment by DillonN** [comment]
Many viruses out there run mining programs on the victim's computer, most people wouldn't notice and just think their PC is getting sluggish. NHM gets flagged since it is a program that runs miners and your antivirus thinks you don't know that. 

It's something AVG has to fix

**Comment by Johann1982** [comment]
Get rid of AVG, it is just as bad as a virus. Rather install bitdefender's free version and add your nicehash folder to exception.

**Comment by S74nk0** [comment]
@giosal A lot of mining software is being bundled by malware authors and Anti Virus programs usually flag the bundled software as well and sadly NiceHash Miner is no exception. NiceHash Miner is open source and anybody can verify that there isn't any malicious activity. This issue is not new, it has been opened before, as there were many **false positives** reported by **AV software**.
Closing issue...
