### ISSUE TITLE
Issues benchmarking Intel CPU with cryptonight algo

### ISSUE THREAD

**Issue by Callah91** [nicehash/NiceHashMiner-Archived#707]
I cant seem to get my New gaming rig set up With the CPU miner. My intel i5 6400 quad core processor gets skipped everytime i try benchmarking...

Please advice if there is anything i can do or change
[log.zip](https://github.com/nicehash/NiceHashMiner/files/825424/log.zip)

**Comment by S74nk0** [comment]
@Callah91 I believe this issue is resolved in one of the [pre-releases](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) (try using the latest one). Please test if [pre-releases](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre) works for you, if it does close the issue if not zip the whole logs folder and post it here.

**Comment by Callah91** [comment]
Issue was resolved with PR #9.
