### ISSUE TITLE
30% rejected shares in dual mining

### ISSUE THREAD

**Issue by nerdatwork** [nicehash/NiceHashMiner-Archived#725]
No matter which secondary algo I try, decred, pascal or lbry, it always has around 30 to 50% rejected shares. What could be causing it ? The main algo ETH is working perfectly.

**Comment by nerdatwork** [comment]
![image](https://cloud.githubusercontent.com/assets/15882196/23980998/7e04fd18-0a29-11e7-941e-db6e5b43c1d9.png)

**Comment by BARUCHER777** [comment]
At me the same problem, but only with other algorithm, and on double mining!

**Comment by kenshirothefist** [comment]
Dual mining with Ethereum + Decred is considered [**experimental**](https://github.com/nicehash/NiceHashMiner/wiki/Enable-ClaymoreDual-with-Decred-Lbry-Pascal), because Claymore's Decred stratum implementation is not fully compatible with NiceHash. We notified Claymore about this and as soon as he will release a new version of his miner with this issue fixed, we'll include it into NHM. Closing this for now.

**Comment by N8Thrasher** [comment]
Even not dual mining Im getiing 100% rejected shares

**Comment by nerdatwork** [comment]
@N8Thrasher Did you upgrade to latest version ? It has lowered my rejected shares to merely 2% now.

**Comment by ghost** [comment]
@nerdatwork - Latest version of what exactly? Thanks.

**Comment by mgwojcik** [comment]
Got the same problem. Mining goes for hours, but finally always crashes due to too many rejection. Any downclocking an downvolting is not helpful...  [Claymore v9.7, AMD drivers updated to 17.7.2]
