### ISSUE TITLE
Dual mining very match rejected to algo DECRED! Claymore's Dual Miner v8.1

### ISSUE THREAD

**Issue by BARUCHER777** [nicehash/NiceHashMiner-Archived#729]
Very much to reject on double mining through a software - Claymore's Dual Ethereum+Decred_Siacoin_Lbry_Pascal AMD+NVIDIA GPU Miner v8.1

Why then a lot of failures (reject`s)  for the algorithm DECRED (DCR)

**Comment by kenshirothefist** [comment]
Dual mining with Ethereum + Decred is considered **experimental**, because Claymore's Decred stratum implementation is not fully compatible with NiceHash. We notified Claymore about this and as soon as he will release a new version of his miner with this issue fixed, we'll include it into NHM. Closing this for now.
