### ISSUE TITLE
Nicehas Miner Exception

### ISSUE THREAD

**Issue by UnclWish** [nicehash/NiceHashMiner-Archived#74]
When begins to mine ethereum today NHM starts to give exception error:
System.NullReferenceException: В экземпляре объекта не задана ссылка на объект.
   в NiceHashMiner.Miner._Start()
   в NiceHashMiner.Miner.Restart()
   в NiceHashMiner.Form1.MinerStatsCheck_Tick(Object sender, EventArgs e)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

In log.txt writes:
[INFO] [Ethereum] Exception: System.Exception: GetCurrentBlock returns null..
   в NiceHashMiner.Ethereum.CreateDAGFile(String worker)

I don't know after what HSM starts to give this error. Yesterday it's mine ethereum normal...
Manual starting ether-proxy and after ethminer.exe with parameters from early log.txt works fine.

**Comment by SpekOregonian** [comment]
Only hours ago this issue began to occur. 

Here is the complete output of the exception.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at NiceHashMiner.Miner._Start()
   at NiceHashMiner.Miner.Restart()
   at NiceHashMiner.Form1.MinerStatsCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

NiceHashMiner
    Assembly Version: 1.3.0.3
    Win32 Version: 1.3.0.3

##     CodeBase: file:///C:/NiceHashMiner_v1.3.0.3/NiceHashMiner.exe

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8681 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Management
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622

##     CodeBase: file:///C:/NiceHashMiner_v1.3.0.3/Newtonsoft.Json.DLL

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8679 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8677 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0

##     CodeBase: file:///C:/NiceHashMiner_v1.3.0.3/log4net.DLL

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)

##     CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by UnclWish** [comment]
It's working again! What's that was? I don't understand...

**Comment by theLosers106** [comment]
It tried to get the current block for the ethereum from https://etherchain.org/api/blocks/count but failed.. That is what causing that error.. So I'll be closing this issue now..
