### ISSUE TITLE
List of errors collected last night

### ISSUE THREAD

**Issue by HennethAnnun** [nicehash/NiceHashMiner-Archived#758]
Hi,

since last week I see the mining rig got unstable. It goes either black screen and needs a reboot or the Nicehash miner gets turned off. Attached a list of errors found last night (the rig ketp mining) followed by a self reboot in the morning.

1. nvlddmkm error every 2 - 3 hours. On occurence system sends around 100 - 120 errors at once (same date, time, second). There are 2 types and they occur one after another:
Variable String too Large
NVRM: Graphics TEX Exception on (GPC 2, TPC 4): TEX NACK / Page Fault

Errors occured at:
2017-03-26 12:19:17 AM
2017-03-26 12:28:31 AM
2017-03-26 01:09:21 AM
2017-03-26 03:27:40 AM
2017-03-26 05:48:07 AM
2017-03-26 07:50:17 AM

Those correlate to my rig switching to mining Lyra2REv2 (attached screenshot).

2. in the morning: Microsoft-Windows-Kernel-Power, Microsoft-Windows-WER-SystemErrorReporting

Also, on logon, I see notifications in the Action Center (attached), that ethminer.exe has been blocked from accessing Graphics hardware.

The rig:
Windows 10 Enterprise, 64-bit
2 x Intel Xeon E5-2620 v4 2.10GHz
3 x Asus GTX 1070 8GB

Latest NiceHash Miner v1.7.5.7

Nothing runs on the rig except the miner.

BR

Henneth

![20170326_error_accessing_graphics_hardware](https://cloud.githubusercontent.com/assets/26388511/24329667/852dcc0a-120d-11e7-867e-43ff0180f902.jpg)

[20170326_Notes.txt](https://github.com/nicehash/NiceHashMiner/files/870625/20170326_Notes.txt)

![20170326_lyra2rev2_chart](https://cloud.githubusercontent.com/assets/26388511/24329779/c175cad4-1210-11e7-8ddc-f4be694c77bd.jpeg)

**Comment by nicehashdev** [comment]
There is nothing much we can do regarding driver crashes - these issues are for NVIDIA to address. You may report them to NVIDIA.

You can try enlarging your virtual memory.

You can try disabling windows defender and see if that is related to ethminer.exe being blocked.

Also, you need to make sure your overclock is stable. Note that when switching algorithms, your cards will briefly go into p0 state where memory clock is much higher than in p2 state. What seems to be stable when you are already in p2 state is not true in p0 state. The cause of most of crashes is due to too high memory overclock. We are working on excavator which will have runtime algorithm switching, so there is no p0-p2 state changes during algorithm change thus more stability.

**Comment by kenshirothefist** [comment]
This seems to be a hardware or hardware/os or hardware/os/driver issue. Try what @nicehashdev suggested, if it does not help try to do a fresh install of windows. If issue persists you might be facing a partially faulted GPU (please note that under mining the GPU is fully-stressed and will be more prone to failures if it is somehow faulted).
