### ISSUE TITLE
DaggerHasimotto issue Nvidia GTX 660

### ISSUE THREAD

**Issue by Headhunter1231994** [nicehash/NiceHashMiner-Archived#764]
Hi I used Nicehash 1.7.3.5 for a while with the GTX 660. Because only that version supported Dagger Hasimotto for the GTX 660. Plus, that is the algorithm which generated the most profit. As of today, I get a out of memory error. Why is this?

System specs:

Windows 7
Fx-6300 
8 GB Ram
GTX 660

**Comment by S74nk0** [comment]
@Headhunter1231994 This is because your GPU doesn't have enough RAM for generating DAG. The limit was increased because of this. Disable DaggerHasimotto for this GPU or use the latest version and NiceHash Miner (it is disabled by default not available for GPUs with insufficient RAM).

Closing issue...

**Comment by Headhunter1231994** [comment]
So  are you saying that the difficulty is increased? Or are you saying the memory required to generate the DAG file is increased to prevent use of old GPu's?

**Comment by S74nk0** [comment]
[difficulty](http://ethereum.stackexchange.com/questions/426/what-is-the-current-dag-size-when-do-we-expect-to-hit-gpu-limits)

**Comment by Headhunter1231994** [comment]
Oh ok! Well... Mining with a GTX 660 is useless then..... Went from 1,12 USD on Dagger to 0,60 USD on Decred.....
