### ISSUE TITLE
nicehash miner not working

### ISSUE THREAD

**Issue by addictedindian** [nicehash/NiceHashMiner-Archived#770]
![log](https://cloud.githubusercontent.com/assets/26764336/24448863/0cf2715e-1493-11e7-8e72-73a78c57c5b4.jpg)

hello all when i go to benchmark process it shows tha following error

"this programme cant start because api-ms-win-crt--runtime-[1-1-0.dll is missing from your computer"

**Comment by S74nk0** [comment]
@addictedindian Please specify what OS version are you using (ex. Windows 7 PRO SP1, Win 8.1...).
Make sure you have https://www.microsoft.com/en-us/download/details.aspx?id=48145 installed. Report back if this solves your issue and give more information about your system.

**Comment by sachadechef** [comment]
I have the same error but with the following dll file "api-ms-win-crt-heap-l1-1-0.dll" 
My OS is Win Srv 2012R2

**Comment by almoharebh** [comment]
https://www.dll-files.com/api-ms-win-crt-heap-l1-1-0.dll.html

here the file download here [https://www.dll-files.com/api-ms-win-crt-heap-l1-1-0.dll.html](url)

**Comment by kenshirothefist** [comment]
@addictedindian please report back if you were able to solve the issues.

**Comment by monev79** [comment]
hello i have problem with last version on windows7
not detect any cpu on my computer
can you help me someway to fix?
thank you in advance

**Comment by Mahesakardun** [comment]
![untitled](https://cloud.githubusercontent.com/assets/27015108/24804278/cafa2464-1b62-11e7-928a-f41bf11ef10c.jpg)

**Comment by Mahesakardun** [comment]
I just started to try it with my old pc.... at 1st, everything is fine.... I close it, restart my pc, do a little experiment with cpu and gpu setting, runing it again, and that is the result..... any advice? meanwhile I'm gonna try Minergate.... newbie miner like me should learn a lot before made final decision to made investment in mining seriously, or just take it as fun hobby..... thanks anyway

**Comment by kenshirothefist** [comment]
@Mahesakardun you should explain a bit more what do you mean by "old PC". In your case this seems to be an issue with internet connectivity. Please take a look at [this FAQ](https://www.nicehash.com/index.jsp?p=faq#faqs13) and try different locations.

@monev79 please make sure you have a compatible CPU, see also [this wiki](https://github.com/nicehash/NiceHashMiner/wiki/Notes-and-hints-on-CPU-mining).

@addictedindian didn't respond after a few solutions were given to him, there we're closing this issue now.

**Comment by Mahesakardun** [comment]
![4](https://cloud.githubusercontent.com/assets/27015108/24849595/b88dc326-1df6-11e7-9523-968d92f9e064.jpg)
this is my old pc specification....

**Comment by Mahesakardun** [comment]
![5](https://cloud.githubusercontent.com/assets/27015108/24849621/e0d7bec2-1df6-11e7-8585-0a83b48cbab3.jpg)
this is my cpu benchmark...

**Comment by Mahesakardun** [comment]
![6](https://cloud.githubusercontent.com/assets/27015108/24849639/f94966cc-1df6-11e7-8898-4e47bb2e52de.jpg)
this is my GPU benchmark....

**Comment by Mahesakardun** [comment]
![7](https://cloud.githubusercontent.com/assets/27015108/24849810/a570d642-1df7-11e7-9f94-56f134bdc314.jpg)

@kenshirothefist  if is because of internet connectivity, then  why it could run in 1st attempt? or else, how come it could work in minergate? (ignore the result, like I said earlier, I wanna to learn it 1st)
@monev79 any advice what kind of decent CPU I should Built? well just enough result to pay my net and electricity bill ? 
@addictedindian  sorry for late response.... I'm still working at my office...

**Comment by kenshirothefist** [comment]
@Mahesakardun I'm afraid your testing PC is too slow to make relevant benchmarks. The disconnects might happen because the system is to slow to produce enough hashing shares per particular time period / time span. To make relevant comparison benchmarks you should use a recent Intel Core i5/i7 CPU or AMD Ryzen CPU and AMD Radeon R9/RX series or NVIDIA 9xx/10xx series GPU.

**Comment by Mahesakardun** [comment]
@kenshirothefist  yeah, some guys in other forum told me the same thing, and I'm gonna start built new pc.... thanks bro.... :)

**Comment by Mahesakardun** [comment]
anyway... can I use more than 1 or multiple PC to mining in nicehash? I'm still configure out the heat on quad vs dual cross fire....
