### ISSUE TITLE
stratum subscribe timeout on every GPU algorithm

### ISSUE THREAD

**Issue by joliver225** [nicehash/NiceHashMiner-Archived#793]
All I do is install nicehash, benchmark all algorithms for CPU and GPU, then click start.  I had no problems until I went from 1.7.5.4 to 1.7.5.9.    

NVidia = 381.65
Win Firewall is turned off
No AV
Defender has an exception for the folder

It appears the only algorithm that connects to anything is CryptoNight.  Both my GPUs show 0 across the board unless I use CryptoNight which is terrible.

Like I said, it wasn't a problem until that upgrade.  I tried deleting the folders and going back, rebenchmarking, and now the older version is doing the same thing.

![capture](https://cloud.githubusercontent.com/assets/27326518/24940175/a596eca6-1f0f-11e7-8713-a746758aaac6.PNG)

**Comment by nicehashdev** [comment]
It looks like you have been temporarily banned. You can try switching to another service location or wait few hours.

**Comment by patrickemuller** [comment]
@nicehashdev I'm having the exactly same problem. But in my case I couldn't mine since I joined the NiceHash and downloaded the program. I can only mine using CPU. Benchmarks are OK and run smoothly, but when I try to mine on GPU every single Algorithm get denied to connect. Tried 2 days in a row and couldn't get it working. Any ideas? I'm using NiceHash Miner version v1.7.5.13
