### ISSUE TITLE
Overheating GTX1070 mini

### ISSUE THREAD

**Issue by Johann1982** [nicehash/NiceHashMiner-Archived#841]
Hi, is there a setting where I can set a maximum temp for my GPU's? Currently they are running at around 80degrees celcius. I would like it to run at max 69degrees.

**Comment by Johann1982** [comment]
Or is there maybe a way to set usage to 90% instead of 100% ?

**Comment by nicehashdev** [comment]
You can use third party apps such as MSI Afterburner to control fan speed.

You can reduce intensity, read here: https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters

But instead of reducing intensity, we recommend reducing TDP, which you can do with MSI Afterburner.

**Comment by Johann1982** [comment]
Thank you. Afterburner worked like a charm. Cards are steady at 60degrees

**Comment by aidonaks** [comment]
@nicehashdev 

> You can reduce intensity, read here: https://github.com/nicehash/NiceHashMiner/wiki/Algorithm-ExtraLaunchParameters

Edit: _Some context might help - I started using NHM on May 21st so I'm in the foetal stage I suppose_

How does one use these or other advanced user parameters on the Windows 10 NHM GUI? I can't seem to find the help files for that on Github or Nicehash.com. Would appreciate your help in finding a way I can get from a novice who wants to learn _(while sticking to Windows 10)_ to an expert who knows exactly what to do to maximize (1) stability and (2) profitability, in that order. Everything interesting on NHM@ Github in that regard seems Linux oriented. 

I'm willing to do the reading and the testing, just need a written guide, since a human one is an impossible dream. ;-)  Nothing seems to exist for advanced Windows users, it's like it's assumed we're all point-and-clickers (which may not be entirely unfair for most NHM windows users)
