### ISSUE TITLE
Only CryptoNight

### ISSUE THREAD

**Issue by GovetaXV** [nicehash/NiceHashMiner-Archived#893]
Hey!,
It only shows the CryptoNight algorithm and not any other, I am using version 1.7.5.12

**Comment by giosal** [comment]
Does show only Cryptonight for CPU?

Does it show other algos for GPU?

George Salukvadze
ATLAS Expert System Team
CERN EP-UAT
CH-1211 Geneva 23
Office: 3196-1-035
Tel: +41 22 766 36 76
Mob: +33 7 88 76 44 88

Sent from Mail for Windows 10

**Comment by startailcoon** [comment]
Same issue here. Only CryptoNight algo is available for mining in the miner. Testing on a computer with only CPU mining available tough, but expecting some more than one algo possible, like HOdl for example.

**Comment by giosal** [comment]
This has been like this since several version. Crytonight is the most profitable algo for CPU, and in previous version, when there were several algos for CPU, it was mining Cryptonight always, it was nearly 10 times more profitable. Guess that’s why they removed other algos.

George Salukvadze
ATLAS Expert System Team
CERN EP-UAT
CH-1211 Geneva 23
Office: 3196-1-035
Tel: +41 22 766 36 76
Mob: +33 7 88 76 44 88

Sent from Mail for Windows 10

**Comment by S74nk0** [comment]
CPU has only **CryptoNight** algorithm.
Closing issue...
