### ISSUE TITLE
Mining with two different Nvidia cards

### ISSUE THREAD

**Issue by Claybro31** [nicehash/NiceHashMiner-Archived#904]
Is it possible to mine with a 1070 and a 1080ti at the same time? I just bought a 1080 ti for 4k 60hz gaming, and was going to sell my 1070, but now I am thinking I could leave it in and mine with it 24/7. Is this possible with nicehash, or do the cards have to be the same?

**Comment by Squall-Leonhart** [comment]
Cards do not have to be the same.

**Comment by AngryOverlord** [comment]
I currently have the same set up of 1070 and 1080ti and they mine just fine with turning one off or mining both at the same time and they will choose which algorithm to mine separately.

**Comment by Claybro31** [comment]
You are the best! Thanks!

**Comment by Claybro31** [comment]
By the way Angry, what PSU do you use? Do you think my 650w Gold will be enough for both cards?

**Comment by AngryOverlord** [comment]
That probably very much depends on the wattage you set, I have mine running slightly under powered so that my total system runs at ~400W so 650 should be fine, but if you over power it to get a good over clock it might have issues. (For note I have a Corsair AX860i which gives wattage readings through USB) I think I currently have them both set to 75% But I also have the EVGA FTW version of the cards which both use 2x8 pins which can pull more power than the default cards.
